/*
Copyright (©) 2016 Hannu Väisänen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


package peltomaa.sukija.voikko;

import java.util.HashMap;
import java.util.Map;
class MapClass {
  public static final Map<String,String[]> map = new HashMap<String,String[]>();
  static {
    map.put ("adaptaatio", new String[]{"adaptaatio", "adaptatio", "adaptatsioni", "adaptatsiooni", });
    map.put ("agitaatio", new String[]{"agitaatio", "agitatio", "agitatsioni", "agitatsiooni", });
    map.put ("allokaatio", new String[]{"allokaatio", "allokatio", "allokatsioni", "allokatsiooni", });
    map.put ("amputaatio", new String[]{"amputaatio", "amputatio", "amputatsioni", "amputatsiooni", });
    map.put ("animaatio", new String[]{"animaatio", "animatio", "animatsioni", "animatsiooni", });
    map.put ("argumentaatio", new String[]{"argumentaatio", "argumentatio", "argumentatsioni", "argumentatsiooni", });
    map.put ("artikulaatio", new String[]{"artikulaatio", "artikulatio", "artikulatsioni", "artikulatsiooni", });
    map.put ("assimilaatio", new String[]{"assimilaatio", "assimilatio", "assimilatsioni", "assimilatsiooni", });
    map.put ("assosiaatio", new String[]{"assosiaatio", "assosiatio", "assosiatsioni", "assosiatsiooni", });
    map.put ("automaatio", new String[]{"automaatio", "automatio", "automatsioni", "automatsiooni", });
    map.put ("deflaatio", new String[]{"deflaatio", "deflatio", "deflatsioni", "deflatsiooni", });
    map.put ("deformaatio", new String[]{"deformaatio", "deformatio", "deformatsioni", "deformatsiooni", });
    map.put ("defreskaatio", new String[]{"defreskaatio", "defreskatio", "defreskatsioni", "defreskatsiooni", });
    map.put ("degeneraatio", new String[]{"degeneraatio", "degeneratio", "degeneratsioni", "degeneratsiooni", });
    map.put ("deklinaatio", new String[]{"deklinaatio", "deklinatio", "deklinatsioni", "deklinatsiooni", });
    map.put ("dekoraatio", new String[]{"dekoraatio", "dekoratio", "dekoratsioni", "dekoratsiooni", });
    map.put ("delegaatio", new String[]{"delegaatio", "delegatio", "delegatsioni", "delegatsiooni", });
    map.put ("delekaatio", new String[]{"delekaatio", "delekatio", "delekatsioni", "delekatsiooni", });
    map.put ("demarkaatio", new String[]{"demarkaatio", "demarkatio", "demarkatsioni", "demarkatsiooni", });
    map.put ("demonstraatio", new String[]{"demonstraatio", "demonstratio", "demonstratsioni", "demonstratsiooni", });
    map.put ("devalvaatio", new String[]{"devalvaatio", "devalvatio", "devalvatsioni", "devalvatsiooni", });
    map.put ("dokumentaatio", new String[]{"dokumentaatio", "dokumentatio", "dokumentatsioni", "dokumentatsiooni", });
    map.put ("elevaatio", new String[]{"elevaatio", "elevatio", "elevatsioni", "elevatsiooni", });
    map.put ("emansipaatio", new String[]{"emansipaatio", "emansipatio", "emansipatsioni", "emansipatsiooni", });
    map.put ("estimaatio", new String[]{"estimaatio", "estimatio", "estimatsioni", "estimatsiooni", });
    map.put ("evaluaatio", new String[]{"evaluaatio", "evaluatio", "evaluatsioni", "evaluatsiooni", });
    map.put ("federaatio", new String[]{"federaatio", "federatio", "federatsioni", "federatsiooni", });
    map.put ("fiksaatio", new String[]{"fiksaatio", "fiksatio", "fiksatsioni", "fiksatsiooni", });
    map.put ("frustraatio", new String[]{"frustraatio", "frustratio", "frustratsioni", "frustratsiooni", });
    map.put ("geminaatio", new String[]{"geminaatio", "geminatio", "geminatsioni", "geminatsiooni", });
    map.put ("globalisaatio", new String[]{"globalisaatio", "globalisatio", "globalisatsioni", "globalisatsiooni", });
    map.put ("gravitaatio", new String[]{"gravitaatio", "gravitatio", "gravitatsioni", "gravitatsiooni", });
    map.put ("hallusinaatio", new String[]{"hallusinaatio", "hallusinatio", "hallusinatsioni", "hallusinatsiooni", });
    map.put ("imitaatio", new String[]{"imitaatio", "imitatio", "imitatsioni", "imitatsiooni", });
    map.put ("improvisaatio", new String[]{"improvisaatio", "improvisatio", "improvisatsioni", "improvisatsiooni", });
    map.put ("indikaatio", new String[]{"indikaatio", "indikatio", "indikatsioni", "indikatsiooni", });
    map.put ("inflaatio", new String[]{"inflaatio", "inflatio", "inflatsioni", "inflatsiooni", });
    map.put ("informaatio", new String[]{"informaatio", "informatio", "informatsioni", "informatsiooni", });
    map.put ("inhalaatio", new String[]{"inhalaatio", "inhalatio", "inhalatsioni", "inhalatsiooni", });
    map.put ("initiaatio", new String[]{"initiaatio", "initiatio", "initiatsioni", "initiatsiooni", });
    map.put ("inkarnaatio", new String[]{"inkarnaatio", "inkarnatio", "inkarnatsioni", "inkarnatsiooni", });
    map.put ("innovaatio", new String[]{"innovaatio", "innovatio", "innovatsioni", "innovatsiooni", });
    map.put ("inspiraatio", new String[]{"inspiraatio", "inspiratio", "inspiratsioni", "inspiratsiooni", });
    map.put ("integraatio", new String[]{"integraatio", "integratio", "integratsioni", "integratsiooni", });
    map.put ("interpolaatio", new String[]{"interpolaatio", "interpolatio", "interpolatsioni", "interpolatsiooni", });
    map.put ("intonaatio", new String[]{"intonaatio", "intonatio", "intonatsioni", "intonatsiooni", });
    map.put ("isolaatio", new String[]{"isolaatio", "isolatio", "isolatsioni", "isolatsiooni", });
    map.put ("iteraatio", new String[]{"iteraatio", "iteratio", "iteratsioni", "iteratsiooni", });
    map.put ("kastraatio", new String[]{"kastraatio", "kastratio", "kastratsioni", "kastratsiooni", });
    map.put ("kirjoitin", new String[]{"kirjoit", "kirjot", });
    map.put ("kodifikaatio", new String[]{"kodifikaatio", "kodifikatio", "kodifikatsioni", "kodifikatsiooni", });
    map.put ("kombinaatio", new String[]{"kombinaatio", "kombinatio", "kombinatsioni", "kombinatsiooni", });
    map.put ("kommunikaatio", new String[]{"kommunikaatio", "kommunikatio", "kommunikatsioni", "kommunikatsiooni", });
    map.put ("komparaatio", new String[]{"komparaatio", "komparatio", "komparatsioni", "komparatsiooni", });
    map.put ("kompensaatio", new String[]{"kompensaatio", "kompensatio", "kompensatsioni", "kompensatsiooni", });
    map.put ("komplikaatio", new String[]{"komplikaatio", "komplikatio", "komplikatsioni", "komplikatsiooni", });
    map.put ("kondensaatio", new String[]{"kondensaatio", "kondensatio", "kondensatsioni", "kondensatsiooni", });
    map.put ("konfiguraatio", new String[]{"konfiguraatio", "konfiguratio", "konfiguratsioni", "konfiguratsiooni", });
    map.put ("konfirmaatio", new String[]{"konfirmaatio", "konfirmatio", "konfirmatsioni", "konfirmatsiooni", });
    map.put ("konjugaatio", new String[]{"konjugaatio", "konjugatio", "konjugatsioni", "konjugatsiooni", });
    map.put ("konnotaatio", new String[]{"konnotaatio", "konnotatio", "konnotatsioni", "konnotatsiooni", });
    map.put ("konsultaatio", new String[]{"konsultaatio", "konsultatio", "konsultatsioni", "konsultatsiooni", });
    map.put ("kooperaatio", new String[]{"kooperaatio", "kooperatio", "kooperatsioni", "kooperatsiooni", });
    map.put ("koordinaatio", new String[]{"koordinaatio", "koordinatio", "koordinatsioni", "koordinatsiooni", });
    map.put ("korporaatio", new String[]{"korporaatio", "korporatio", "korporatsioni", "korporatsiooni", });
    map.put ("korrelaatio", new String[]{"korrelaatio", "korrelatio", "korrelatsioni", "korrelatsiooni", });
    map.put ("kulminaatio", new String[]{"kulminaatio", "kulminatio", "kulminatsioni", "kulminatsiooni", });
    map.put ("kumulaatio", new String[]{"kumulaatio", "kumulatio", "kumulatsioni", "kumulatsiooni", });
    map.put ("kvalifikaatio", new String[]{"kvalifikaatio", "kvalifikatio", "kvalifikatsioni", "kvalifikatsiooni", });
    map.put ("levitaatio", new String[]{"levitaatio", "levitatio", "levitatsioni", "levitatsiooni", });
    map.put ("lokalisaatio", new String[]{"lokalisaatio", "lokalisatio", "lokalisatsioni", "lokalisatsiooni", });
    map.put ("manipulaatio", new String[]{"manipulaatio", "manipulatio", "manipulatsioni", "manipulatsiooni", });
    map.put ("masturbaatio", new String[]{"masturbaatio", "masturbatio", "masturbatsioni", "masturbatsiooni", });
    map.put ("materialisaatio", new String[]{"materialisaatio", "materialisatio", "materialisatsioni", "materialisatsiooni", });
    map.put ("meditaatio", new String[]{"meditaatio", "meditatio", "meditatsioni", "meditatsiooni", });
    map.put ("menstruaatio", new String[]{"menstruaatio", "menstruatio", "menstruatsioni", "menstruatsiooni", });
    map.put ("migraatio", new String[]{"migraatio", "migratio", "migratsioni", "migratsiooni", });
    map.put ("mobilisaatio", new String[]{"mobilisaatio", "mobilisatio", "mobilisatsioni", "mobilisatsiooni", });
    map.put ("modifikaatio", new String[]{"modifikaatio", "modifikatio", "modifikatsioni", "modifikatsiooni", });
    map.put ("modulaatio", new String[]{"modulaatio", "modulatio", "modulatsioni", "modulatsiooni", });
    map.put ("motivaatio", new String[]{"motivaatio", "motivatio", "motivatsioni", "motivatsiooni", });
    map.put ("mutaatio", new String[]{"mutaatio", "mutatio", "mutatsioni", "mutatsiooni", });
    map.put ("mystifikaatio", new String[]{"mystifikaatio", "mystifikatio", "mystifikatsioni", "mystifikatsiooni", });
    map.put ("navigaatio", new String[]{"navigaatio", "navigatio", "navigatsioni", "navigatsiooni", });
    map.put ("negaatio", new String[]{"negaatio", "negatio", "negatsioni", "negatsiooni", });
    map.put ("neutralisaatio", new String[]{"neutralisaatio", "neutralisatio", "neutralisatsioni", "neutralisatsiooni", });
    map.put ("normalisaatio", new String[]{"normalisaatio", "normalisatio", "normalisatsioni", "normalisatsiooni", });
    map.put ("notaatio", new String[]{"notaatio", "notatio", "notatsioni", "notatsiooni", });
    map.put ("nutaatio", new String[]{"nutaatio", "nutatio", "nutatsioni", "nutatsiooni", });
    map.put ("obligaatio", new String[]{"obligaatio", "obligatio", "obligatsioni", "obligatsiooni", });
    map.put ("operaatio", new String[]{"operaatio", "operatio", "operatsioni", "operatsiooni", });
    map.put ("organisaatio", new String[]{"organisaatio", "organisatio", "organisatsioni", "organisatsiooni", });
    map.put ("orientaatio", new String[]{"orientaatio", "orientatio", "orientatsioni", "orientatsiooni", });
    map.put ("oskillaatio", new String[]{"oskillaatio", "oskillatio", "oskillatsioni", "oskillatsiooni", });
    map.put ("osoitin", new String[]{"osoit", "osot", });
    map.put ("ovulaatio", new String[]{"ovulaatio", "ovulatio", "ovulatsioni", "ovulatsiooni", });
    map.put ("personifikaatio", new String[]{"personifikaatio", "personifikatio", "personifikatsioni", "personifikatsiooni", });
    map.put ("polarisaatio", new String[]{"polarisaatio", "polarisatio", "polarisatsioni", "polarisatsiooni", });
    map.put ("populaatio", new String[]{"populaatio", "populatio", "populatsioni", "populatsiooni", });
    map.put ("predestinaatio", new String[]{"predestinaatio", "predestinatio", "predestinatsioni", "predestinatsiooni", });
    map.put ("propagaatio", new String[]{"propagaatio", "propagatio", "propagatsioni", "propagatsiooni", });
    map.put ("provisio", new String[]{"provisio", "provisioni", "provisiooni", });
    map.put ("provokaatio", new String[]{"provokaatio", "provokatio", "provokatsioni", "provokatsiooni", });
    map.put ("rajoitin", new String[]{"rajoit", "rajot", });
    map.put ("realisaatio", new String[]{"realisaatio", "realisatio", "realisatsioni", "realisatsiooni", });
    map.put ("reformaatio", new String[]{"reformaatio", "reformatio", "reformatsioni", "reformatsiooni", });
    map.put ("rehabilitaatio", new String[]{"rehabilitaatio", "rehabilitatio", "rehabilitatsioni", "rehabilitatsiooni", });
    map.put ("reklamaatio", new String[]{"reklamaatio", "reklamatio", "reklamatsioni", "reklamatsiooni", });
    map.put ("relaatio", new String[]{"relaatio", "relatio", "relatsioni", "relatsiooni", });
    map.put ("restauraatio", new String[]{"restauraatio", "restauratio", "restauratsioni", "restauratsiooni", });
    map.put ("revalvaatio", new String[]{"revalvaatio", "revalvatio", "revalvatsioni", "revalvatsiooni", });
    map.put ("rotaatio", new String[]{"rotaatio", "rotatio", "rotatsioni", "rotatsiooni", });
    map.put ("segregaatio", new String[]{"segregaatio", "segregatio", "segregatsioni", "segregatsiooni", });
    map.put ("sekoitin", new String[]{"sekoit", "sekot", });
    map.put ("sensaatio", new String[]{"sensaatio", "sensatio", "sensatsioni", "sensatsiooni", });
    map.put ("sentralisaatio", new String[]{"sentralisaatio", "sentralisatio", "sentralisatsioni", "sentralisatsiooni", });
    map.put ("sivilisaatio", new String[]{"sivilisaatio", "sivilisatio", "sivilisatsioni", "sivilisatsiooni", });
    map.put ("sosialisaatio", new String[]{"sosialisaatio", "sosialisatio", "sosialisatsioni", "sosialisatsiooni", });
    map.put ("spekulaatio", new String[]{"spekulaatio", "spekulatio", "spekulatsioni", "spekulatsiooni", });
    map.put ("spesifikaatio", new String[]{"spesifikaatio", "spesifikatio", "spesifikatsioni", "spesifikatsiooni", });
    map.put ("stagnaatio", new String[]{"stagnaatio", "stagnatio", "stagnatsioni", "stagnatsiooni", });
    map.put ("sterilisaatio", new String[]{"sterilisaatio", "sterilisatio", "sterilisatsioni", "sterilisatsiooni", });
    map.put ("teroitin", new String[]{"teroit", "terot", });
    map.put ("topikalisaatio", new String[]{"topikalisaatio", "topikalisatio", "topikalisatsioni", "topikalisatsiooni", });
    map.put ("transformaatio", new String[]{"transformaatio", "transformatio", "transformatsioni", "transformatsiooni", });
    map.put ("translaatio", new String[]{"translaatio", "translatio", "translatsioni", "translatsiooni", });
    map.put ("undulaatio", new String[]{"undulaatio", "undulatio", "undulatsioni", "undulatsiooni", });
    map.put ("variaatio", new String[]{"variaatio", "variatio", "variatsioni", "variatsiooni", });
    map.put ("ventilaatio", new String[]{"ventilaatio", "ventilatio", "ventilatsioni", "ventilatsiooni", });
    map.put ("verifikaatio", new String[]{"verifikaatio", "verifikatio", "verifikatsioni", "verifikatsiooni", });
    map.put ("viivoitin", new String[]{"viivoit", "viivot", });
    map.put ("somatisaatio", new String[]{"somatisaatio", "somatisatio", "somatisatsioni", "somatisatsiooni", });
    map.put ("stimulaatio", new String[]{"stimulaatio", "stimulatio", "stimulatsioni", "stimulatsiooni", });
    map.put ("saturaatio", new String[]{"saturaatio", "saturatio", "saturatsioni", "saturatsiooni", });
    map.put ("permutaatio", new String[]{"permutaatio", "permutatio", "permutatsioni", "permutatsiooni", });
    map.put ("prekarisaatio", new String[]{"prekarisaatio", "prekarisatio", "prekarisatsioni", "prekarisatsiooni", });
    map.put ("indoktrinaatio", new String[]{"indoktrinaatio", "indoktrinatio", "indoktrinatsioni", "indoktrinatsiooni", });
    map.put ("akkommodaatio", new String[]{"akkommodaatio", "akkommodatio", "akkommodatsioni", "akkommodatsiooni", });
    map.put ("aktivaatio", new String[]{"aktivaatio", "aktivatio", "aktivatsioni", "aktivatsiooni", });
    map.put ("auskultaatio", new String[]{"auskultaatio", "auskultatio", "auskultatsioni", "auskultatsiooni", });
    map.put ("falsifikaatio", new String[]{"falsifikaatio", "falsifikatio", "falsifikatsioni", "falsifikatsiooni", });
    map.put ("teleportaatio", new String[]{"teleportaatio", "teleportatio", "teleportatsioni", "teleportatsiooni", });
    map.put ("individualisaatio", new String[]{"individualisaatio", "individualisatio", "individualisatsioni", "individualisatsiooni", });
    map.put ("fellaatio", new String[]{"fellaatio", "fellatio", "fellatsioni", "fellatsiooni", });
    map.put ("ejakulaatio", new String[]{"ejakulaatio", "ejakulatio", "ejakulatsioni", "ejakulatsiooni", });
    map.put ("simulaatio", new String[]{"simulaatio", "simulatio", "simulatsioni", "simulatsiooni", });
    map.put ("kausaatio", new String[]{"kausaatio", "kausatio", "kausatsioni", "kausatsiooni", });
    map.put ("emulaatio", new String[]{"emulaatio", "emulatio", "emulatsioni", "emulatsiooni", });
    map.put ("predikaatio", new String[]{"predikaatio", "predikatio", "predikatsioni", "predikatsiooni", });
    map.put ("denotaatio", new String[]{"denotaatio", "denotatio", "denotatsioni", "denotatsiooni", });
    map.put ("deviaatio", new String[]{"deviaatio", "deviatio", "deviatsioni", "deviatsiooni", });
    map.put ("identifikaatio", new String[]{"identifikaatio", "identifikatio", "identifikatsioni", "identifikatsiooni", });
    map.put ("installaatio", new String[]{"installaatio", "installatio", "installatsioni", "installatsiooni", });
    map.put ("ionisaatio", new String[]{"ionisaatio", "ionisatio", "ionisatsioni", "ionisatsiooni", });
    map.put ("immunisaatio", new String[]{"immunisaatio", "immunisatio", "immunisatsioni", "immunisatsiooni", });
    map.put ("ilmoitin", new String[]{"ilmoit", "ilmot", });
    map.put ("regeneraatio", new String[]{"regeneraatio", "regeneratio", "regeneratsioni", "regeneratsiooni", });
    map.put ("resignaatio", new String[]{"resignaatio", "resignatio", "resignatsioni", "resignatsiooni", });
    map.put ("kavitaatio", new String[]{"kavitaatio", "kavitatio", "kavitatsioni", "kavitatsiooni", });
    map.put ("implementaatio", new String[]{"implementaatio", "implementatio", "implementatsioni", "implementatsiooni", });
    map.put ("regulaatio", new String[]{"regulaatio", "regulatio", "regulatsioni", "regulatsiooni", });
    map.put ("kristallisaatio", new String[]{"kristallisaatio", "kristallisatio", "kristallisatsioni", "kristallisatsiooni", });
    map.put ("sublimaatio", new String[]{"sublimaatio", "sublimatio", "sublimatsioni", "sublimatsiooni", });
    map.put ("penetraatio", new String[]{"penetraatio", "penetratio", "penetratsioni", "penetratsiooni", });
    map.put ("mekanisaatio", new String[]{"mekanisaatio", "mekanisatio", "mekanisatsioni", "mekanisatsiooni", });
    map.put ("sekularisaatio", new String[]{"sekularisaatio", "sekularisatio", "sekularisatsioni", "sekularisatsiooni", });
    map.put ("aberraatio", new String[]{"aberraatio", "aberratio", "aberratsioni", "aberratsiooni", });
    map.put ("ablaatio", new String[]{"ablaatio", "ablatio", "ablatsioni", "ablatsiooni", });
    map.put ("varoitin", new String[]{"varoit", "varot", });
    map.put ("hiekoitin", new String[]{"hiekoit", "hiekot", });
    map.put ("kartoitin", new String[]{"kartoit", "kartot", });
    map.put ("lannoitin", new String[]{"lannoit", "lannot", });
    map.put ("tasoitin", new String[]{"tasoit", "tasot", });
    map.put ("virroitin", new String[]{"virroit", "virrot", });
    map.put ("eliminaatio", new String[]{"eliminaatio", "eliminatio", "eliminatsioni", "eliminatsiooni", });
    map.put ("ekskommunikaatio", new String[]{"ekskommunikaatio", "ekskommunikatio", "ekskommunikatsioni", "ekskommunikatsiooni", });
    map.put ("vietnamisaatio", new String[]{"vietnamisaatio", "vietnamisatio", "vietnamisatsioni", "vietnamisatsiooni", });
    map.put ("deklamaatio", new String[]{"deklamaatio", "deklamatio", "deklamatsioni", "deklamatsiooni", });
    map.put ("inkubaatio", new String[]{"inkubaatio", "inkubatio", "inkubatsioni", "inkubatsiooni", });
    map.put ("mineralisaatio", new String[]{"mineralisaatio", "mineralisatio", "mineralisatsioni", "mineralisatsiooni", });
    map.put ("replikaatio", new String[]{"replikaatio", "replikatio", "replikatsioni", "replikatsiooni", });
    map.put ("perforaatio", new String[]{"perforaatio", "perforatio", "perforatsioni", "perforatsiooni", });
    map.put ("konsentraatio", new String[]{"konsentraatio", "konsentratio", "konsentratsioni", "konsentratsiooni", });
    map.put ("akkumulaatio", new String[]{"akkumulaatio", "akkumulatio", "akkumulatsioni", "akkumulatsiooni", });
    map.put ("konformaatio", new String[]{"konformaatio", "konformatio", "konformatsioni", "konformatsiooni", });
    map.put ("litteraatio", new String[]{"litteraatio", "litteratio", "litteratsioni", "litteratsiooni", });
    map.put ("reduplikaatio", new String[]{"reduplikaatio", "reduplikatio", "reduplikatsioni", "reduplikatsiooni", });
    map.put ("urbanisaatio", new String[]{"urbanisaatio", "urbanisatio", "urbanisatsioni", "urbanisatsiooni", });
    map.put ("illustraatio", new String[]{"illustraatio", "illustratio", "illustratsioni", "illustratsiooni", });
    map.put ("implantaatio", new String[]{"implantaatio", "implantatio", "implantatsioni", "implantatsiooni", });
    map.put ("fermentaatio", new String[]{"fermentaatio", "fermentatio", "fermentatsioni", "fermentatsiooni", });
    map.put ("fosforylaatio", new String[]{"fosforylaatio", "fosforylatio", "fosforylatsioni", "fosforylatsiooni", });
    map.put ("relaksaatio", new String[]{"relaksaatio", "relaksatio", "relaksatsioni", "relaksatsiooni", });
    map.put ("polymerisaatio", new String[]{"polymerisaatio", "polymerisatio", "polymerisatsioni", "polymerisatsiooni", });
    map.put ("fokalisaatio", new String[]{"fokalisaatio", "fokalisatio", "fokalisatsioni", "fokalisatsiooni", });
    map.put ("glukuronidaatio", new String[]{"glukuronidaatio", "glukuronidatio", "glukuronidatsioni", "glukuronidatsiooni", });
    map.put ("medikalisaatio", new String[]{"medikalisaatio", "medikalisatio", "medikalisatsioni", "medikalisatsiooni", });
    map.put ("dislokaatio", new String[]{"dislokaatio", "dislokatio", "dislokatsioni", "dislokatsiooni", });
    map.put ("disputaatio", new String[]{"disputaatio", "disputatio", "disputatsioni", "disputatsiooni", });
    map.put ("dissosiaatio", new String[]{"dissosiaatio", "dissosiatio", "dissosiatsioni", "dissosiatsiooni", });
    map.put ("palpaatio", new String[]{"palpaatio", "palpatio", "palpatsioni", "palpatsiooni", });
    map.put ("luksaatio", new String[]{"luksaatio", "luksatio", "luksatsioni", "luksatsiooni", });
    map.put ("kolonisaatio", new String[]{"kolonisaatio", "kolonisatio", "kolonisatsioni", "kolonisatsiooni", });
    map.put ("personalisaatio", new String[]{"personalisaatio", "personalisatio", "personalisatsioni", "personalisatsiooni", });
    map.put ("militarisaatio", new String[]{"militarisaatio", "militarisatio", "militarisatsioni", "militarisatsiooni", });
    map.put ("hydraatio", new String[]{"hydraatio", "hydratio", "hydratsioni", "hydratsiooni", });
    map.put ("parametrisaatio", new String[]{"parametrisaatio", "parametrisatio", "parametrisatsioni", "parametrisatsiooni", });
    map.put ("visualisaatio", new String[]{"visualisaatio", "visualisatio", "visualisatsioni", "visualisatsiooni", });
    map.put ("idealisaatio", new String[]{"idealisaatio", "idealisatio", "idealisatsioni", "idealisatsiooni", });
    map.put ("suturaatio", new String[]{"suturaatio", "suturatio", "suturatsioni", "suturatsiooni", });
    map.put ("aspiraatio", new String[]{"aspiraatio", "aspiratio", "aspiratsioni", "aspiratsiooni", });
    map.put ("inflammaatio", new String[]{"inflammaatio", "inflammatio", "inflammatsioni", "inflammatsiooni", });
    map.put ("intubaatio", new String[]{"intubaatio", "intubatio", "intubatsioni", "intubatsiooni", });
    map.put ("kontaminaatio", new String[]{"kontaminaatio", "kontaminatio", "kontaminatsioni", "kontaminatsiooni", });
    map.put ("intoksikaatio", new String[]{"intoksikaatio", "intoksikatio", "intoksikatsioni", "intoksikatsiooni", });
    map.put ("desorientaatio", new String[]{"desorientaatio", "desorientatio", "desorientatsioni", "desorientatsiooni", });
    map.put ("herniaatio", new String[]{"herniaatio", "herniatio", "herniatsioni", "herniatsiooni", });
    map.put ("sedaatio", new String[]{"sedaatio", "sedatio", "sedatsioni", "sedatsiooni", });
    map.put ("modernisaatio", new String[]{"modernisaatio", "modernisatio", "modernisatsioni", "modernisatsiooni", });
    map.put ("industrialisaatio", new String[]{"industrialisaatio", "industrialisatio", "industrialisatsioni", "industrialisatsiooni", });
    map.put ("konfederaatio", new String[]{"konfederaatio", "konfederatio", "konfederatsioni", "konfederatsiooni", });
    map.put ("granulaatio", new String[]{"granulaatio", "granulatio", "granulatsioni", "granulatsiooni", });
    map.put ("tamponaatio", new String[]{"tamponaatio", "tamponatio", "tamponatsioni", "tamponatsiooni", });
    map.put ("aggregaatio", new String[]{"aggregaatio", "aggregatio", "aggregatsioni", "aggregatsiooni", });
    map.put ("irritaatio", new String[]{"irritaatio", "irritatio", "irritatsioni", "irritatsiooni", });
    map.put ("pigmentaatio", new String[]{"pigmentaatio", "pigmentatio", "pigmentatsioni", "pigmentatsiooni", });
    map.put ("palpitaatio", new String[]{"palpitaatio", "palpitatio", "palpitatsioni", "palpitatsiooni", });
    map.put ("angulaatio", new String[]{"angulaatio", "angulatio", "angulatsioni", "angulatsiooni", });
    map.put ("dilataatio", new String[]{"dilataatio", "dilatatio", "dilatatsioni", "dilatatsiooni", });
    map.put ("koarktaatio", new String[]{"koarktaatio", "koarktatio", "koarktatsioni", "koarktatsiooni", });
    map.put ("proliferaatio", new String[]{"proliferaatio", "proliferatio", "proliferatsioni", "proliferatsiooni", });
    map.put ("eksitaatio", new String[]{"eksitaatio", "eksitatio", "eksitatsioni", "eksitatsiooni", });
    map.put ("akkulturaatio", new String[]{"akkulturaatio", "akkulturatio", "akkulturatsioni", "akkulturatsiooni", });
    map.put ("kalibraatio", new String[]{"kalibraatio", "kalibratio", "kalibratsioni", "kalibratsiooni", });
    map.put ("augmentaatio", new String[]{"augmentaatio", "augmentatio", "augmentatsioni", "augmentatsiooni", });
    map.put ("faskikulaatio", new String[]{"faskikulaatio", "faskikulatio", "faskikulatsioni", "faskikulatsiooni", });
    map.put ("hydroksylaatio", new String[]{"hydroksylaatio", "hydroksylatio", "hydroksylatsioni", "hydroksylatsiooni", });
    map.put ("oksidaatio", new String[]{"oksidaatio", "oksidatio", "oksidatsioni", "oksidatsiooni", });
    map.put ("salivaatio", new String[]{"salivaatio", "salivatio", "salivatsioni", "salivatsiooni", });
    map.put ("androgenisaatio", new String[]{"androgenisaatio", "androgenisatio", "androgenisatsioni", "androgenisatsiooni", });
    map.put ("applikaatio", new String[]{"applikaatio", "applikatio", "applikatsioni", "applikatsiooni", });
    map.put ("fibrillaatio", new String[]{"fibrillaatio", "fibrillatio", "fibrillatsioni", "fibrillatsiooni", });
    map.put ("ekstubaatio", new String[]{"ekstubaatio", "ekstubatio", "ekstubatsioni", "ekstubatsiooni", });
    map.put ("embolisaatio", new String[]{"embolisaatio", "embolisatio", "embolisatsioni", "embolisatsiooni", });
    map.put ("feminisaatio", new String[]{"feminisaatio", "feminisatio", "feminisatsioni", "feminisatsiooni", });
    map.put ("fertilisaatio", new String[]{"fertilisaatio", "fertilisatio", "fertilisatsioni", "fertilisatsiooni", });
    map.put ("filtraatio", new String[]{"filtraatio", "filtratio", "filtratsioni", "filtratsiooni", });
    map.put ("nitrifikaatio", new String[]{"nitrifikaatio", "nitrifikatio", "nitrifikatsioni", "nitrifikatsiooni", });
    map.put ("ekskoriaatio", new String[]{"ekskoriaatio", "ekskoriatio", "ekskoriatsioni", "ekskoriatsiooni", });
    map.put ("eradikaatio", new String[]{"eradikaatio", "eradikatio", "eradikatsioni", "eradikatsiooni", });
    map.put ("habituaatio", new String[]{"habituaatio", "habituatio", "habituatsioni", "habituatsiooni", });
    map.put ("instillaatio", new String[]{"instillaatio", "instillatio", "instillatsioni", "instillatsiooni", });
    map.put ("virilisaatio", new String[]{"virilisaatio", "virilisatio", "virilisatsioni", "virilisatsiooni", });
    map.put ("habilitaatio", new String[]{"habilitaatio", "habilitatio", "habilitatsioni", "habilitatsiooni", });
    map.put ("eksudaatio", new String[]{"eksudaatio", "eksudatio", "eksudatsioni", "eksudatsiooni", });
    map.put ("gestaatio", new String[]{"gestaatio", "gestatio", "gestatsioni", "gestatsiooni", });
    map.put ("induraatio", new String[]{"induraatio", "induratio", "induratsioni", "induratsiooni", });
    map.put ("infiltraatio", new String[]{"infiltraatio", "infiltratio", "infiltratsioni", "infiltratsiooni", });
    map.put ("kalsifikaatio", new String[]{"kalsifikaatio", "kalsifikatio", "kalsifikatsioni", "kalsifikatsiooni", });
    map.put ("konstipaatio", new String[]{"konstipaatio", "konstipatio", "konstipatsioni", "konstipatsiooni", });
    map.put ("lakrimaatio", new String[]{"lakrimaatio", "lakrimatio", "lakrimatsioni", "lakrimatsiooni", });
    map.put ("laktaatio", new String[]{"laktaatio", "laktatio", "laktatsioni", "laktatsiooni", });
    map.put ("laseraatio", new String[]{"laseraatio", "laseratio", "laseratsioni", "laseratsiooni", });
    map.put ("manifestaatio", new String[]{"manifestaatio", "manifestatio", "manifestatsioni", "manifestatsiooni", });
    map.put ("maseraatio", new String[]{"maseraatio", "maseratio", "maseratsioni", "maseratsiooni", });
    map.put ("maskulinisaatio", new String[]{"maskulinisaatio", "maskulinisatio", "maskulinisatsioni", "maskulinisatsiooni", });
    map.put ("resuskitaatio", new String[]{"resuskitaatio", "resuskitatio", "resuskitatsioni", "resuskitatsiooni", });
    map.put ("ulseraatio", new String[]{"ulseraatio", "ulseratio", "ulseratsioni", "ulseratsiooni", });
    map.put ("retardaatio", new String[]{"retardaatio", "retardatio", "retardatsioni", "retardatsiooni", });
    map.put ("hydrogenaatio", new String[]{"hydrogenaatio", "hydrogenatio", "hydrogenatsioni", "hydrogenatsiooni", });
    map.put ("konsolidaatio", new String[]{"konsolidaatio", "konsolidatio", "konsolidatsioni", "konsolidatsiooni", });
    map.put ("laksaatio", new String[]{"laksaatio", "laksatio", "laksatsioni", "laksatsiooni", });
    map.put ("infestaatio", new String[]{"infestaatio", "infestatio", "infestatsioni", "infestatsiooni", });
    map.put ("obstipaatio", new String[]{"obstipaatio", "obstipatio", "obstipatsioni", "obstipatsiooni", });
    map.put ("opsonisaatio", new String[]{"opsonisaatio", "opsonisatio", "opsonisatsioni", "opsonisatsiooni", });
    map.put ("ossifikaatio", new String[]{"ossifikaatio", "ossifikatio", "ossifikatsioni", "ossifikatsiooni", });
    map.put ("keratinisaatio", new String[]{"keratinisaatio", "keratinisatio", "keratinisatsioni", "keratinisatsiooni", });
    map.put ("eksfoliaatio", new String[]{"eksfoliaatio", "eksfoliatio", "eksfoliatsioni", "eksfoliatsiooni", });
    map.put ("differentiaatio", new String[]{"differentiaatio", "differentiatio", "differentiatsioni", "differentiatsiooni", });
    map.put ("pronaatio", new String[]{"pronaatio", "pronatio", "pronatsioni", "pronatsiooni", });
    map.put ("regurgitaatio", new String[]{"regurgitaatio", "regurgitatio", "regurgitatsioni", "regurgitatsiooni", });
    map.put ("vaskularisaatio", new String[]{"vaskularisaatio", "vaskularisatio", "vaskularisatsioni", "vaskularisatsiooni", });
    map.put ("digitalisaatio", new String[]{"digitalisaatio", "digitalisatio", "digitalisatsioni", "digitalisatsiooni", });
    map.put ("eksaserbaatio", new String[]{"eksaserbaatio", "eksaserbatio", "eksaserbatsioni", "eksaserbatsiooni", });
    map.put ("inseminaatio", new String[]{"inseminaatio", "inseminatio", "inseminatsioni", "inseminatsiooni", });
    map.put ("ekstrapolaatio", new String[]{"ekstrapolaatio", "ekstrapolatio", "ekstrapolatsioni", "ekstrapolatsiooni", });
    map.put ("vakuolisaatio", new String[]{"vakuolisaatio", "vakuolisatio", "vakuolisatsioni", "vakuolisatsiooni", });
    map.put ("disseminaatio", new String[]{"disseminaatio", "disseminatio", "disseminatsioni", "disseminatsiooni", });
    map.put ("duplikaatio", new String[]{"duplikaatio", "duplikatio", "duplikatsioni", "duplikatsiooni", });
    map.put ("eksploraatio", new String[]{"eksploraatio", "eksploratio", "eksploratsioni", "eksploratsiooni", });
    map.put ("evakuaatio", new String[]{"evakuaatio", "evakuatio", "evakuatsioni", "evakuatsiooni", });
    map.put ("fenestraatio", new String[]{"fenestraatio", "fenestratio", "fenestratsioni", "fenestratsiooni", });
    map.put ("invaginaatio", new String[]{"invaginaatio", "invaginatio", "invaginatsioni", "invaginatsiooni", });
    map.put ("katetrisaatio", new String[]{"katetrisaatio", "katetrisatio", "katetrisatsioni", "katetrisatsiooni", });
    map.put ("klaudikaatio", new String[]{"klaudikaatio", "klaudikatio", "klaudikatsioni", "klaudikatsiooni", });
    map.put ("malrotaatio", new String[]{"malrotaatio", "malrotatio", "malrotatsioni", "malrotatsiooni", });
    map.put ("marsupialisaatio", new String[]{"marsupialisaatio", "marsupialisatio", "marsupialisatsioni", "marsupialisatsiooni", });
    map.put ("metylaatio", new String[]{"metylaatio", "metylatio", "metylatsioni", "metylatsiooni", });
    map.put ("sugillaatio", new String[]{"sugillaatio", "sugillatio", "sugillatsioni", "sugillatsiooni", });
    map.put ("asetylaatio", new String[]{"asetylaatio", "asetylatio", "asetylatsioni", "asetylatsiooni", });
    map.put ("deprivaatio", new String[]{"deprivaatio", "deprivatio", "deprivatsioni", "deprivatsiooni", });
    map.put ("malformaatio", new String[]{"malformaatio", "malformatio", "malformatsioni", "malformatsiooni", });
    map.put ("myelinaatio", new String[]{"myelinaatio", "myelinatio", "myelinatsioni", "myelinatsiooni", });
    map.put ("trabekulaatio", new String[]{"trabekulaatio", "trabekulatio", "trabekulatsioni", "trabekulatsiooni", });
    map.put ("renovaatio", new String[]{"renovaatio", "renovatio", "renovatsioni", "renovatsiooni", });
    map.put ("bifurkaatio", new String[]{"bifurkaatio", "bifurkatio", "bifurkatsioni", "bifurkatsiooni", });
    map.put ("konisaatio", new String[]{"konisaatio", "konisatio", "konisatsioni", "konisatsiooni", });
    map.put ("krepitaatio", new String[]{"krepitaatio", "krepitatio", "krepitatsioni", "krepitatsiooni", });
    map.put ("pulsaatio", new String[]{"pulsaatio", "pulsatio", "pulsatsioni", "pulsatsiooni", });
    map.put ("strangulaatio", new String[]{"strangulaatio", "strangulatio", "strangulatsioni", "strangulatsiooni", });
    map.put ("formikaatio", new String[]{"formikaatio", "formikatio", "formikatsioni", "formikatsiooni", });
    map.put ("agglutinaatio", new String[]{"agglutinaatio", "agglutinatio", "agglutinatsioni", "agglutinatsiooni", });
    map.put ("kapasitaatio", new String[]{"kapasitaatio", "kapasitatio", "kapasitatsioni", "kapasitatsiooni", });
    map.put ("konfabulaatio", new String[]{"konfabulaatio", "konfabulatio", "konfabulatsioni", "konfabulatsiooni", });
    map.put ("translitteraatio", new String[]{"translitteraatio", "translitteratio", "translitteratsioni", "translitteratsiooni", });
    map.put ("annihilaatio", new String[]{"annihilaatio", "annihilatio", "annihilatsioni", "annihilatsiooni", });
    map.put ("fluktuaatio", new String[]{"fluktuaatio", "fluktuatio", "fluktuatsioni", "fluktuatsiooni", });
    map.put ("konfrontaatio", new String[]{"konfrontaatio", "konfrontatio", "konfrontatsioni", "konfrontatsiooni", });
    map.put ("karbonylaatio", new String[]{"karbonylaatio", "karbonylatio", "karbonylatsioni", "karbonylatsiooni", });
    map.put ("allitteraatio", new String[]{"allitteraatio", "allitteratio", "allitteratsioni", "allitteratsiooni", });
    map.put ("trepanaatio", new String[]{"trepanaatio", "trepanatio", "trepanatsioni", "trepanatsiooni", });
    map.put ("domestikaatio", new String[]{"domestikaatio", "domestikatio", "domestikatsioni", "domestikatsiooni", });
    map.put ("ekstirpaatio", new String[]{"ekstirpaatio", "ekstirpatio", "ekstirpatsioni", "ekstirpatsiooni", });
    map.put ("narraatio", new String[]{"narraatio", "narratio", "narratsioni", "narratsiooni", });
    map.put ("enukleaatio", new String[]{"enukleaatio", "enukleatio", "enukleatsioni", "enukleatsiooni", });
    map.put ("lateralisaatio", new String[]{"lateralisaatio", "lateralisatio", "lateralisatsioni", "lateralisatsiooni", });
    map.put ("myelinisaatio", new String[]{"myelinisaatio", "myelinisatio", "myelinisatsioni", "myelinisatsiooni", });
    map.put ("palliaatio", new String[]{"palliaatio", "palliatio", "palliatsioni", "palliatsiooni", });
    map.put ("stigmatisaatio", new String[]{"stigmatisaatio", "stigmatisatio", "stigmatisatsioni", "stigmatisatsiooni", });
    map.put ("vegetaatio", new String[]{"vegetaatio", "vegetatio", "vegetatsioni", "vegetatsiooni", });
    map.put ("vitrifikaatio", new String[]{"vitrifikaatio", "vitrifikatio", "vitrifikatsioni", "vitrifikatsiooni", });
    map.put ("deklaraatio", new String[]{"deklaraatio", "deklaratio", "deklaratsioni", "deklaratsiooni", });
    map.put ("eskalaatio", new String[]{"eskalaatio", "eskalatio", "eskalatsioni", "eskalatsiooni", });
    map.put ("inokulaatio", new String[]{"inokulaatio", "inokulatio", "inokulatsioni", "inokulatsiooni", });
    map.put ("elongaatio", new String[]{"elongaatio", "elongatio", "elongatsioni", "elongatsiooni", });
    map.put ("insolaatio", new String[]{"insolaatio", "insolatio", "insolatsioni", "insolatsiooni", });
    map.put ("kanonisaatio", new String[]{"kanonisaatio", "kanonisatio", "kanonisatsioni", "kanonisatsiooni", });
    map.put ("kontemplaatio", new String[]{"kontemplaatio", "kontemplatio", "kontemplatsioni", "kontemplatsiooni", });
    map.put ("polymeraatio", new String[]{"polymeraatio", "polymeratio", "polymeratsioni", "polymeratsiooni", });
    map.put ("ammonifikaatio", new String[]{"ammonifikaatio", "ammonifikatio", "ammonifikatsioni", "ammonifikatsiooni", });
    map.put ("saltaatio", new String[]{"saltaatio", "saltatio", "saltatsioni", "saltatsiooni", });
    map.put ("demetylaatio", new String[]{"demetylaatio", "demetylatio", "demetylatsioni", "demetylatsiooni", });
    map.put ("glykosylaatio", new String[]{"glykosylaatio", "glykosylatio", "glykosylatsioni", "glykosylatsiooni", });
    map.put ("gastrulaatio", new String[]{"gastrulaatio", "gastrulatio", "gastrulatsioni", "gastrulatsiooni", });
    map.put ("konurbaatio", new String[]{"konurbaatio", "konurbatio", "konurbatsioni", "konurbatsiooni", });
    map.put ("inklinaatio", new String[]{"inklinaatio", "inklinatio", "inklinatsioni", "inklinatsiooni", });
    map.put ("emanaatio", new String[]{"emanaatio", "emanatio", "emanatsioni", "emanatsiooni", });
    map.put ("islamisaatio", new String[]{"islamisaatio", "islamisatio", "islamisatsioni", "islamisatsiooni", });
    map.put ("alkylaatio", new String[]{"alkylaatio", "alkylatio", "alkylatsioni", "alkylatsiooni", });
    map.put ("akklimatisaatio", new String[]{"akklimatisaatio", "akklimatisatio", "akklimatisatsioni", "akklimatisatsiooni", });
    map.put ("sedimentaatio", new String[]{"sedimentaatio", "sedimentatio", "sedimentatsioni", "sedimentatsiooni", });
    map.put ("sanitaatio", new String[]{"sanitaatio", "sanitatio", "sanitatsioni", "sanitatsiooni", });
    map.put ("kompilaatio", new String[]{"kompilaatio", "kompilatio", "kompilatsioni", "kompilatsiooni", });
    map.put ("relegaatio", new String[]{"relegaatio", "relegatio", "relegatsioni", "relegatsiooni", });
    map.put ("ahavoittaa", new String[]{"ahavoit", "ahavot", });
    map.put ("ahmaista", new String[]{"ahmais", "ahmas", });
    map.put ("ajoittaa", new String[]{"ajoit", "ajot", });
    map.put ("aloittaa", new String[]{"aloit", "alot", });
    map.put ("ammottaa", new String[]{"ammot", "ammoit", });
    map.put ("ampaista", new String[]{"ampais", "ampas", });
    map.put ("armoittaa", new String[]{"armoit", "armot", });
    map.put ("arvioittaa", new String[]{"arvioit", "arviot", });
    map.put ("arvottaa", new String[]{"arvot", "arvoit", });
    map.put ("aukaista", new String[]{"aukais", "aukas", });
    map.put ("autioittaa", new String[]{"autioit", "autiot", });
    map.put ("ehdottaa", new String[]{"ehdot", "ehdoit", });
    map.put ("ehkäistä", new String[]{"ehkäis", "ehkäs", });
    map.put ("elävöittää", new String[]{"elävöit", "elävöt", });
    map.put ("erottaa", new String[]{"erot", "eroit", });
    map.put ("haaroittaa", new String[]{"haaroit", "haarot", });
    map.put ("haarottaa", new String[]{"haarot", "haaroit", });
    map.put ("haavoittaa", new String[]{"haavoit", "haavot", });
    map.put ("hahmottaa", new String[]{"hahmot", "hahmoit", });
    map.put ("hajottaa", new String[]{"hajot", "hajoit", });
    map.put ("halaista", new String[]{"halais", "halas", });
    map.put ("halkaista", new String[]{"halkais", "halkas", });
    map.put ("hangoitella", new String[]{"hangoit", "hangot", });
    map.put ("hankaloittaa", new String[]{"hankaloit", "hankalot", });
    map.put ("happamoittaa", new String[]{"happamoit", "happamot", });
    map.put ("hapsottaa", new String[]{"hapsot", "hapsoit", });
    map.put ("harjoittaa", new String[]{"harjoit", "harjot", });
    map.put ("harottaa", new String[]{"harot", "haroit", });
    map.put ("haukottaa", new String[]{"haukot", "haukoit", });
    map.put ("heikottaa", new String[]{"heikot", "heikoit", });
    map.put ("hekottaa", new String[]{"hekot", "hekoit", });
    map.put ("heloittaa", new String[]{"heloit", "helot", });
    map.put ("helottaa", new String[]{"helot", "heloit", });
    map.put ("helpottaa", new String[]{"helpot", "helpoit", });
    map.put ("hemaista", new String[]{"hemais", "hemas", });
    map.put ("hemmotella", new String[]{"hemmot", "hemmoit", });
    map.put ("henkevöittää", new String[]{"henkevöit", "henkevöt", });
    map.put ("henkäistä", new String[]{"henkäis", "henkäs", });
    map.put ("herpaista", new String[]{"herpais", "herpas", });
    map.put ("herroitella", new String[]{"herroit", "herrot", });
    map.put ("hiekoittaa", new String[]{"hiekoit", "hiekot", });
    map.put ("hieraista", new String[]{"hierais", "hieras", });
    map.put ("hierottaa", new String[]{"hierot", "hieroit", });
    map.put ("hihkaista", new String[]{"hihkais", "hihkas", });
    map.put ("hillottaa", new String[]{"hillot", "hilloit", });
    map.put ("himottaa", new String[]{"himot", "himoit", });
    map.put ("hinnoittaa", new String[]{"hinnoit", "hinnot", });
    map.put ("hiottaa", new String[]{"hiot", "hioit", });
    map.put ("hipaista", new String[]{"hipais", "hipas", });
    map.put ("hohottaa", new String[]{"hohot", "hohoit", });
    map.put ("holottaa", new String[]{"holot", "holoit", });
    map.put ("honottaa", new String[]{"honot", "honoit", });
    map.put ("hotkaista", new String[]{"hotkais", "hotkas", });
    map.put ("huikaista", new String[]{"huikais", "huikas", });
    map.put ("huitaista", new String[]{"huitais", "huitas", });
    map.put ("huohottaa", new String[]{"huohot", "huohoit", });
    map.put ("huokaista", new String[]{"huokais", "huokas", });
    map.put ("hutaista", new String[]{"hutais", "hutas", });
    map.put ("huuhtaista", new String[]{"huuhtais", "huuhtas", });
    map.put ("häikäistä", new String[]{"häikäis", "häikäs", });
    map.put ("häpäistä", new String[]{"häpäis", "häpäs", });
    map.put ("häväistä", new String[]{"häväis", "häväs", });
    map.put ("häämöttää", new String[]{"häämöt", "häämöit", });
    map.put ("hökäistä", new String[]{"hökäis", "hökäs", });
    map.put ("hölöttää", new String[]{"hölöt", "hölöit", });
    map.put ("höpöttää", new String[]{"höpöt", "höpöit", });
    map.put ("höröttää", new String[]{"höröt", "höröit", });
    map.put ("hössöttää", new String[]{"hössöt", "hössöit", });
    map.put ("ilmaista", new String[]{"ilmais", "ilmas", });
    map.put ("ilmoittaa", new String[]{"ilmoit", "ilmot", });
    map.put ("ilotella", new String[]{"ilot", "iloit", });
    map.put ("imaista", new String[]{"imais", "imas", });
    map.put ("inhottaa", new String[]{"inhot", "inhoit", });
    map.put ("innoittaa", new String[]{"innoit", "innot", });
    map.put ("irrottaa", new String[]{"irrot", "irroit", });
    map.put ("isotella", new String[]{"isot", "isoit", });
    map.put ("jaksottaa", new String[]{"jaksot", "jaksoit", });
    map.put ("jaloittaa", new String[]{"jaloit", "jalot", });
    map.put ("janottaa", new String[]{"janot", "janoit", });
    map.put ("jaottaa", new String[]{"jaot", "jaoit", });
    map.put ("jauhottaa", new String[]{"jauhot", "jauhoit", });
    map.put ("johdottaa", new String[]{"johdot", "johdoit", });
    map.put ("jomottaa", new String[]{"jomot", "jomoit", });
    map.put ("jonottaa", new String[]{"jonot", "jonoit", });
    map.put ("julkaista", new String[]{"julkais", "julkas", });
    map.put ("juopotella", new String[]{"juopot", "juopoit", });
    map.put ("juottaa", new String[]{"juot", "juoit", });
    map.put ("jurottaa", new String[]{"jurot", "juroit", });
    map.put ("jököttää", new String[]{"jököt", "jököit", });
    map.put ("jöröttää", new String[]{"jöröt", "jöröit", });
    map.put ("kaapaista", new String[]{"kaapais", "kaapas", });
    map.put ("kaavoittaa", new String[]{"kaavoit", "kaavot", });
    map.put ("kadottaa", new String[]{"kadot", "kadoit", });
    map.put ("kahmaista", new String[]{"kahmais", "kahmas", });
    map.put ("kakaista", new String[]{"kakais", "kakas", });
    map.put ("kaljoitella", new String[]{"kaljoit", "kaljot", });
    map.put ("kammottaa", new String[]{"kammot", "kammoit", });
    map.put ("kansoittaa", new String[]{"kansoit", "kansot", });
    map.put ("karaista", new String[]{"karais", "karas", });
    map.put ("karjaista", new String[]{"karjais", "karjas", });
    map.put ("karkaista", new String[]{"karkais", "karkas", });
    map.put ("karkottaa", new String[]{"karkot", "karkoit", });
    map.put ("karmaista", new String[]{"karmais", "karmas", });
    map.put ("kartoittaa", new String[]{"kartoit", "kartot", });
    map.put ("katkaista", new String[]{"katkais", "katkas", });
    map.put ("katkeroittaa", new String[]{"katkeroit", "katkerot", });
    map.put ("kauhaista", new String[]{"kauhais", "kauhas", });
    map.put ("kehaista", new String[]{"kehais", "kehas", });
    map.put ("kehottaa", new String[]{"kehot", "kehoit", });
    map.put ("keinotella", new String[]{"keinot", "keinoit", });
    map.put ("kellottaa", new String[]{"kellot", "kelloit", });
    map.put ("keplotella", new String[]{"keplot", "keploit", });
    map.put ("kiekaista", new String[]{"kiekais", "kiekas", });
    map.put ("kietaista", new String[]{"kietais", "kietas", });
    map.put ("kiihottaa", new String[]{"kiihot", "kiihoit", });
    map.put ("kiillottaa", new String[]{"kiillot", "kiilloit", });
    map.put ("kiljaista", new String[]{"kiljais", "kiljas", });
    map.put ("kilvoitella", new String[]{"kilvoit", "kilvot", });
    map.put ("kipaista", new String[]{"kipais", "kipas", });
    map.put ("kirjoittaa", new String[]{"kirjoit", "kirjot", });
    map.put ("kirkaista", new String[]{"kirkais", "kirkas", });
    map.put ("kirpaista", new String[]{"kirpais", "kirpas", });
    map.put ("kirvoittaa", new String[]{"kirvoit", "kirvot", });
    map.put ("kiskaista", new String[]{"kiskais", "kiskas", });
    map.put ("kiskottaa", new String[]{"kiskot", "kiskoit", });
    map.put ("kiusoitella", new String[]{"kiusoit", "kiusot", });
    map.put ("kohottaa", new String[]{"kohot", "kohoit", });
    map.put ("kolhaista", new String[]{"kolhais", "kolhas", });
    map.put ("kollottaa", new String[]{"kollot", "kolloit", });
    map.put ("kolottaa", new String[]{"kolot", "koloit", });
    map.put ("korottaa", new String[]{"korot", "koroit", });
    map.put ("kotkottaa", new String[]{"kotkot", "kotkoit", });
    map.put ("kouraista", new String[]{"kourais", "kouras", });
    map.put ("kulottaa", new String[]{"kulot", "kuloit", });
    map.put ("kumottaa", new String[]{"kumot", "kumoit", });
    map.put ("kunnioittaa", new String[]{"kunnioit", "kunniot", });
    map.put ("kurkottaa", new String[]{"kurkot", "kurkoit", });
    map.put ("kurottaa", new String[]{"kurot", "kuroit", });
    map.put ("kuumoittaa", new String[]{"kuumoit", "kuumot", });
    map.put ("kuumottaa", new String[]{"kuumot", "kuumoit", });
    map.put ("kuvottaa", new String[]{"kuvot", "kuvoit", });
    map.put ("kydöttää", new String[]{"kydöt", "kydöit", });
    map.put ("kysäistä", new String[]{"kysäis", "kysäs", });
    map.put ("kyyhöttää", new String[]{"kyyhöt", "kyyhöit", });
    map.put ("käväistä", new String[]{"käväis", "käväs", });
    map.put ("kääräistä", new String[]{"kääräis", "kääräs", });
    map.put ("kököttää", new String[]{"kököt", "kököit", });
    map.put ("köllöttää", new String[]{"köllöt", "köllöit", });
    map.put ("könöttää", new String[]{"könöt", "könöit", });
    map.put ("köröttää", new String[]{"köröt", "köröit", });
    map.put ("laatoittaa", new String[]{"laatoit", "laatot", });
    map.put ("lahjoittaa", new String[]{"lahjoit", "lahjot", });
    map.put ("lahottaa", new String[]{"lahot", "lahoit", });
    map.put ("lainoittaa", new String[]{"lainoit", "lainot", });
    map.put ("laiskottaa", new String[]{"laiskot", "laiskoit", });
    map.put ("lakaista", new String[]{"lakais", "lakas", });
    map.put ("langoittaa", new String[]{"langoit", "langot", });
    map.put ("lannoittaa", new String[]{"lannoit", "lannot", });
    map.put ("lassottaa", new String[]{"lassot", "lassoit", });
    map.put ("lastoittaa", new String[]{"lastoit", "lastot", });
    map.put ("laudoittaa", new String[]{"laudoit", "laudot", });
    map.put ("laukaista", new String[]{"laukais", "laukas", });
    map.put ("lekotella", new String[]{"lekot", "lekoit", });
    map.put ("lihottaa", new String[]{"lihot", "lihoit", });
    map.put ("liihottaa", new String[]{"liihot", "liihoit", });
    map.put ("liioitella", new String[]{"liioit", "liiot", });
    map.put ("liipaista", new String[]{"liipais", "liipas", });
    map.put ("liipottaa", new String[]{"liipot", "liipoit", });
    map.put ("linnoittaa", new String[]{"linnoit", "linnot", });
    map.put ("liottaa", new String[]{"liot", "lioit", });
    map.put ("liuottaa", new String[]{"liuot", "liuoit", });
    map.put ("lohkaista", new String[]{"lohkais", "lohkas", });
    map.put ("loilottaa", new String[]{"loilot", "loiloit", });
    map.put ("loimottaa", new String[]{"loimot", "loimoit", });
    map.put ("lorottaa", new String[]{"lorot", "loroit", });
    map.put ("lukaista", new String[]{"lukais", "lukas", });
    map.put ("luotottaa", new String[]{"luotot", "luotoit", });
    map.put ("luottaa", new String[]{"luot", "luoit", });
    map.put ("luulotella", new String[]{"luulot", "luuloit", });
    map.put ("läiskäistä", new String[]{"läiskäis", "läiskäs", });
    map.put ("läpäistä", new String[]{"läpäis", "läpäs", });
    map.put ("lätkäistä", new String[]{"lätkäis", "lätkäs", });
    map.put ("lököttää", new String[]{"lököt", "lököit", });
    map.put ("lörpöttää", new String[]{"lörpöt", "lörpöit", });
    map.put ("lörötellä", new String[]{"löröt", "löröit", });
    map.put ("lötköttää", new String[]{"lötköt", "lötköit", });
    map.put ("maadoittaa", new String[]{"maadoit", "maadot", });
    map.put ("majoittaa", new String[]{"majoit", "majot", });
    map.put ("mataloittaa", new String[]{"mataloit", "matalot", });
    map.put ("miinoittaa", new String[]{"miinoit", "miinot", });
    map.put ("mitoittaa", new String[]{"mitoit", "mitot", });
    map.put ("motkottaa", new String[]{"motkot", "motkoit", });
    map.put ("mulkaista", new String[]{"mulkais", "mulkas", });
    map.put ("murjaista", new String[]{"murjais", "murjas", });
    map.put ("murjottaa", new String[]{"murjot", "murjoit", });
    map.put ("mätkäistä", new String[]{"mätkäis", "mätkäs", });
    map.put ("mököttää", new String[]{"mököt", "mököit", });
    map.put ("möllöttää", new String[]{"möllöt", "möllöit", });
    map.put ("napsaista", new String[]{"napsais", "napsas", });
    map.put ("nauhoittaa", new String[]{"nauhoit", "nauhot", });
    map.put ("neuvotella", new String[]{"neuvot", "neuvoit", });
    map.put ("nielaista", new String[]{"nielais", "nielas", });
    map.put ("nikottaa", new String[]{"nikot", "nikoit", });
    map.put ("nipottaa", new String[]{"nipot", "nipoit", });
    map.put ("niskoitella", new String[]{"niskoit", "niskot", });
    map.put ("niuhottaa", new String[]{"niuhot", "niuhoit", });
    map.put ("nolottaa", new String[]{"nolot", "noloit", });
    map.put ("nuolaista", new String[]{"nuolais", "nuolas", });
    map.put ("nuuhkaista", new String[]{"nuuhkais", "nuuhkas", });
    map.put ("nyhjöttää", new String[]{"nyhjöt", "nyhjöit", });
    map.put ("nyhtäistä", new String[]{"nyhtäis", "nyhtäs", });
    map.put ("nykäistä", new String[]{"nykäis", "nykäs", });
    map.put ("nälväistä", new String[]{"nälväis", "nälväs", });
    map.put ("näykkäistä", new String[]{"näykkäis", "näykkäs", });
    map.put ("nököttää", new String[]{"nököt", "nököit", });
    map.put ("odottaa", new String[]{"odot", "odoit", });
    map.put ("oikaista", new String[]{"oikais", "oikas", });
    map.put ("osoittaa", new String[]{"osoit", "osot", });
    map.put ("pahoittaa", new String[]{"pahoit", "pahot", });
    map.put ("paikoittaa", new String[]{"paikoit", "paikot", });
    map.put ("painottaa", new String[]{"painot", "painoit", });
    map.put ("pakottaa", new String[]{"pakot", "pakoit", });
    map.put ("pallotella", new String[]{"pallot", "palloit", });
    map.put ("paloittaa", new String[]{"paloit", "palot", });
    map.put ("palstoittaa", new String[]{"palstoit", "palstot", });
    map.put ("parkaista", new String[]{"parkais", "parkas", });
    map.put ("pelottaa", new String[]{"pelot", "peloit", });
    map.put ("piilottaa", new String[]{"piilot", "piiloit", });
    map.put ("pilkottaa", new String[]{"pilkot", "pilkoit", });
    map.put ("pingottaa", new String[]{"pingot", "pingoit", });
    map.put ("pinkaista", new String[]{"pinkais", "pinkas", });
    map.put ("pinnoittaa", new String[]{"pinnoit", "pinnot", });
    map.put ("pirskottaa", new String[]{"pirskot", "pirskoit", });
    map.put ("polkaista", new String[]{"polkais", "polkas", });
    map.put ("ponkaista", new String[]{"ponkais", "ponkas", });
    map.put ("porottaa", new String[]{"porot", "poroit", });
    map.put ("posottaa", new String[]{"posot", "posoit", });
    map.put ("potkaista", new String[]{"potkais", "potkas", });
    map.put ("pudottaa", new String[]{"pudot", "pudoit", });
    map.put ("puhkaista", new String[]{"puhkais", "puhkas", });
    map.put ("pujottaa", new String[]{"pujot", "pujoit", });
    map.put ("pullottaa", new String[]{"pullot", "pulloit", });
    map.put ("punoittaa", new String[]{"punoit", "punot", });
    map.put ("punottaa", new String[]{"punot", "punoit", });
    map.put ("puraista", new String[]{"purais", "puras", });
    map.put ("pursottaa", new String[]{"pursot", "pursoit", });
    map.put ("puukottaa", new String[]{"puukot", "puukoit", });
    map.put ("pyyhkäistä", new String[]{"pyyhkäis", "pyyhkäs", });
    map.put ("pörröttää", new String[]{"pörröt", "pörröit", });
    map.put ("pötköttää", new String[]{"pötköt", "pötköit", });
    map.put ("raapaista", new String[]{"raapais", "raapas", });
    map.put ("rahoittaa", new String[]{"rahoit", "rahot", });
    map.put ("raidoittaa", new String[]{"raidoit", "raidot", });
    map.put ("rajoittaa", new String[]{"rajoit", "rajot", });
    map.put ("ramaista", new String[]{"ramais", "ramas", });
    map.put ("rankaista", new String[]{"rankais", "rankas", });
    map.put ("raottaa", new String[]{"raot", "raoit", });
    map.put ("rappioittaa", new String[]{"rappioit", "rappiot", });
    map.put ("rasvoittaa", new String[]{"rasvoit", "rasvot", });
    map.put ("ratkaista", new String[]{"ratkais", "ratkas", });
    map.put ("raudoittaa", new String[]{"raudoit", "raudot", });
    map.put ("rauhoittaa", new String[]{"rauhoit", "rauhot", });
    map.put ("raukaista", new String[]{"raukais", "raukas", });
    map.put ("raunioittaa", new String[]{"raunioit", "rauniot", });
    map.put ("rehevöittää", new String[]{"rehevöit", "rehevöt", });
    map.put ("rehottaa", new String[]{"rehot", "rehoit", });
    map.put ("repsottaa", new String[]{"repsot", "repsoit", });
    map.put ("repäistä", new String[]{"repäis", "repäs", });
    map.put ("reväistä", new String[]{"reväis", "reväs", });
    map.put ("riepottaa", new String[]{"riepot", "riepoit", });
    map.put ("riipaista", new String[]{"riipais", "riipas", });
    map.put ("ripottaa", new String[]{"ripot", "ripoit", });
    map.put ("riuhtaista", new String[]{"riuhtais", "riuhtas", });
    map.put ("rohkaista", new String[]{"rohkais", "rohkas", });
    map.put ("rokottaa", new String[]{"rokot", "rokoit", });
    map.put ("rusottaa", new String[]{"rusot", "rusoit", });
    map.put ("rykäistä", new String[]{"rykäis", "rykäs", });
    map.put ("rääkäistä", new String[]{"rääkäis", "rääkäs", });
    map.put ("röyhtäistä", new String[]{"röyhtäis", "röyhtäs", });
    map.put ("sakottaa", new String[]{"sakot", "sakoit", });
    map.put ("sanoittaa", new String[]{"sanoit", "sanot", });
    map.put ("sanottaa", new String[]{"sanot", "sanoit", });
    map.put ("sarjoittaa", new String[]{"sarjoit", "sarjot", });
    map.put ("saunottaa", new String[]{"saunot", "saunoit", });
    map.put ("seisottaa", new String[]{"seisot", "seisoit", });
    map.put ("sekoittaa", new String[]{"sekoit", "sekot", });
    map.put ("sidottaa", new String[]{"sidot", "sidoit", });
    map.put ("siemaista", new String[]{"siemais", "siemas", });
    map.put ("sijoittaa", new String[]{"sijoit", "sijot", });
    map.put ("silottaa", new String[]{"silot", "siloit", });
    map.put ("sipaista", new String[]{"sipais", "sipas", });
    map.put ("sirottaa", new String[]{"sirot", "siroit", });
    map.put ("sohaista", new String[]{"sohais", "sohas", });
    map.put ("sojottaa", new String[]{"sojot", "sojoit", });
    map.put ("sokaista", new String[]{"sokais", "sokas", });
    map.put ("sopottaa", new String[]{"sopot", "sopoit", });
    map.put ("sukaista", new String[]{"sukais", "sukas", });
    map.put ("survaista", new String[]{"survais", "survas", });
    map.put ("sutaista", new String[]{"sutais", "sutas", });
    map.put ("suukottaa", new String[]{"suukot", "suukoit", });
    map.put ("sylkäistä", new String[]{"sylkäis", "sylkäs", });
    map.put ("syöpötellä", new String[]{"syöpöt", "syöpöit", });
    map.put ("sähköttää", new String[]{"sähköt", "sähköit", });
    map.put ("sönköttää", new String[]{"sönköt", "sönköit", });
    map.put ("söpöttää", new String[]{"söpöt", "söpöit", });
    map.put ("sössöttää", new String[]{"sössöt", "sössöit", });
    map.put ("taksoittaa", new String[]{"taksoit", "taksot", });
    map.put ("tarkoittaa", new String[]{"tarkoit", "tarkot", });
    map.put ("tasoittaa", new String[]{"tasoit", "tasot", });
    map.put ("tauottaa", new String[]{"tauot", "tauoit", });
    map.put ("tavoittaa", new String[]{"tavoit", "tavot", });
    map.put ("tekaista", new String[]{"tekais", "tekas", });
    map.put ("teloittaa", new String[]{"teloit", "telot", });
    map.put ("tempaista", new String[]{"tempais", "tempas", });
    map.put ("teroittaa", new String[]{"teroit", "terot", });
    map.put ("terävöittää", new String[]{"terävöit", "terävöt", });
    map.put ("tiedottaa", new String[]{"tiedot", "tiedoit", });
    map.put ("tipottaa", new String[]{"tipot", "tipoit", });
    map.put ("tiuskaista", new String[]{"tiuskais", "tiuskas", });
    map.put ("toitottaa", new String[]{"toitot", "toitoit", });
    map.put ("toivottaa", new String[]{"toivot", "toivoit", });
    map.put ("tokaista", new String[]{"tokais", "tokas", });
    map.put ("toljottaa", new String[]{"toljot", "toljoit", });
    map.put ("tollottaa", new String[]{"tollot", "tolloit", });
    map.put ("tuijottaa", new String[]{"tuijot", "tuijoit", });
    map.put ("tuottaa", new String[]{"tuot", "tuoit", });
    map.put ("turvottaa", new String[]{"turvot", "turvoit", });
    map.put ("tympäistä", new String[]{"tympäis", "tympäs", });
    map.put ("tökkäistä", new String[]{"tökkäis", "tökkäs", });
    map.put ("töllöttää", new String[]{"töllöt", "töllöit", });
    map.put ("tönäistä", new String[]{"tönäis", "tönäs", });
    map.put ("törröttää", new String[]{"törröt", "törröit", });
    map.put ("töytäistä", new String[]{"töytäis", "töytäs", });
    map.put ("ulottaa", new String[]{"ulot", "uloit", });
    map.put ("unhottaa", new String[]{"unhot", "unhoit", });
    map.put ("upottaa", new String[]{"upot", "upoit", });
    map.put ("uskotella", new String[]{"uskot", "uskoit", });
    map.put ("vaahdottaa", new String[]{"vaahdot", "vaahdoit", });
    map.put ("vahingoittaa", new String[]{"vahingoit", "vahingot", });
    map.put ("vajottaa", new String[]{"vajot", "vajoit", });
    map.put ("vakavoittaa", new String[]{"vakavoit", "vakavot", });
    map.put ("valaista", new String[]{"valais", "valas", });
    map.put ("valkaista", new String[]{"valkais", "valkas", });
    map.put ("valloittaa", new String[]{"valloit", "vallot", });
    map.put ("valottaa", new String[]{"valot", "valoit", });
    map.put ("valvottaa", new String[]{"valvot", "valvoit", });
    map.put ("vannottaa", new String[]{"vannot", "vannoit", });
    map.put ("varoittaa", new String[]{"varoit", "varot", });
    map.put ("vaurioittaa", new String[]{"vaurioit", "vauriot", });
    map.put ("vauroittaa", new String[]{"vauroit", "vaurot", });
    map.put ("veloittaa", new String[]{"veloit", "velot", });
    map.put ("velvoittaa", new String[]{"velvoit", "velvot", });
    map.put ("verottaa", new String[]{"verot", "veroit", });
    map.put ("vetäistä", new String[]{"vetäis", "vetäs", });
    map.put ("viekoittaa", new String[]{"viekoit", "viekot", });
    map.put ("vieroittaa", new String[]{"vieroit", "vierot", });
    map.put ("vihjaista", new String[]{"vihjais", "vihjas", });
    map.put ("vihlaista", new String[]{"vihlais", "vihlas", });
    map.put ("vihoittaa", new String[]{"vihoit", "vihot", });
    map.put ("viipottaa", new String[]{"viipot", "viipoit", });
    map.put ("viitoittaa", new String[]{"viitoit", "viitot", });
    map.put ("viivoittaa", new String[]{"viivoit", "viivot", });
    map.put ("vilkaista", new String[]{"vilkais", "vilkas", });
    map.put ("vilvoittaa", new String[]{"vilvoit", "vilvot", });
    map.put ("vioittaa", new String[]{"vioit", "viot", });
    map.put ("virvoittaa", new String[]{"virvoit", "virvot", });
    map.put ("voihkaista", new String[]{"voihkais", "voihkas", });
    map.put ("voivottaa", new String[]{"voivot", "voivoit", });
    map.put ("vollottaa", new String[]{"vollot", "volloit", });
    map.put ("vouhottaa", new String[]{"vouhot", "vouhoit", });
    map.put ("vuorottaa", new String[]{"vuorot", "vuoroit", });
    map.put ("väkevöittää", new String[]{"väkevöit", "väkevöt", });
    map.put ("värjöttää", new String[]{"värjöt", "värjöit", });
    map.put ("yhtiöittää", new String[]{"yhtiöit", "yhtiöt", });
    map.put ("ylevöittää", new String[]{"ylevöit", "ylevöt", });
    map.put ("yskäistä", new String[]{"yskäis", "yskäs", });
    map.put ("yököttää", new String[]{"yököt", "yököit", });
    map.put ("ähkäistä", new String[]{"ähkäis", "ähkäs", });
    map.put ("ällöttää", new String[]{"ällöt", "ällöit", });
    map.put ("ärjäistä", new String[]{"ärjäis", "ärjäs", });
    map.put ("jaloitella", new String[]{"jaloit", "jalot", });
    map.put ("taustoittaa", new String[]{"taustoit", "taustot", });
    map.put ("touhottaa", new String[]{"touhot", "touhoit", });
    map.put ("huiskaista", new String[]{"huiskais", "huiskas", });
    map.put ("pompottaa", new String[]{"pompot", "pompoit", });
    map.put ("aidoittaa", new String[]{"aidoit", "aidot", });
    map.put ("ansoittaa", new String[]{"ansoit", "ansot", });
    map.put ("hoilottaa", new String[]{"hoilot", "hoiloit", });
    map.put ("jäntevöittää", new String[]{"jäntevöit", "jäntevöt", });
    map.put ("nastoittaa", new String[]{"nastoit", "nastot", });
    map.put ("madottaa", new String[]{"madot", "madoit", });
    map.put ("verkottaa", new String[]{"verkot", "verkoit", });
    map.put ("kuullottaa", new String[]{"kuullot", "kuulloit", });
    map.put ("mölöttää", new String[]{"mölöt", "mölöit", });
    map.put ("molottaa", new String[]{"molot", "moloit", });
    map.put ("pyyhäistä", new String[]{"pyyhäis", "pyyhäs", });
    map.put ("kailottaa", new String[]{"kailot", "kailoit", });
    map.put ("lerpottaa", new String[]{"lerpot", "lerpoit", });
    map.put ("aallottaa", new String[]{"aallot", "aalloit", });
    map.put ("villoittaa", new String[]{"villoit", "villot", });
    map.put ("tölväistä", new String[]{"tölväis", "tölväs", });
    map.put ("solvaista", new String[]{"solvais", "solvas", });
    map.put ("julaista", new String[]{"julais", "julas", });
    map.put ("häippäistä", new String[]{"häippäis", "häippäs", });
    map.put ("hermottaa", new String[]{"hermot", "hermoit", });
    map.put ("hihnoittaa", new String[]{"hihnoit", "hihnot", });
    map.put ("hölpöttää", new String[]{"hölpöt", "hölpöit", });
    map.put ("hömpsöttää", new String[]{"hömpsöt", "hömpsöit", });
    map.put ("hömpöttää", new String[]{"hömpöt", "hömpöit", });
    map.put ("imelöittää", new String[]{"imelöit", "imelöt", });
    map.put ("kirkottaa", new String[]{"kirkot", "kirkoit", });
    map.put ("listoittaa", new String[]{"listoit", "listot", });
    map.put ("läimäistä", new String[]{"läimäis", "läimäs", });
    map.put ("rimoittaa", new String[]{"rimoit", "rimot", });
    map.put ("mellottaa", new String[]{"mellot", "melloit", });
    map.put ("monottaa", new String[]{"monot", "monoit", });
    map.put ("mukavoittaa", new String[]{"mukavoit", "mukavot", });
    map.put ("nasevoittaa", new String[]{"nasevoit", "nasevot", });
    map.put ("naukaista", new String[]{"naukais", "naukas", });
    map.put ("hapottaa", new String[]{"hapot", "hapoit", });
    map.put ("polottaa", new String[]{"polot", "poloit", });
    map.put ("hilpaista", new String[]{"hilpais", "hilpas", });
    map.put ("hotaista", new String[]{"hotais", "hotas", });
    map.put ("hönkäistä", new String[]{"hönkäis", "hönkäs", });
    map.put ("kirmaista", new String[]{"kirmais", "kirmas", });
    map.put ("kuopaista", new String[]{"kuopais", "kuopas", });
    map.put ("kusaista", new String[]{"kusais", "kusas", });
    map.put ("kynsäistä", new String[]{"kynsäis", "kynsäs", });
    map.put ("lipaista", new String[]{"lipais", "lipas", });
    map.put ("nirhaista", new String[]{"nirhais", "nirhas", });
    map.put ("nokkaista", new String[]{"nokkais", "nokkas", });
    map.put ("nuuskaista", new String[]{"nuuskais", "nuuskas", });
    map.put ("nyhjäistä", new String[]{"nyhjäis", "nyhjäs", });
    map.put ("nyppäistä", new String[]{"nyppäis", "nyppäs", });
    map.put ("nyyhkäistä", new String[]{"nyyhkäis", "nyyhkäs", });
    map.put ("pesaista", new String[]{"pesais", "pesas", });
    map.put ("pieraista", new String[]{"pierais", "pieras", });
    map.put ("pätkäistä", new String[]{"pätkäis", "pätkäs", });
    map.put ("roiskaista", new String[]{"roiskais", "roiskas", });
    map.put ("rouhaista", new String[]{"rouhais", "rouhas", });
    map.put ("röhkäistä", new String[]{"röhkäis", "röhkäs", });
    map.put ("silmäistä", new String[]{"silmäis", "silmäs", });
    map.put ("sitaista", new String[]{"sitais", "sitas", });
    map.put ("ulvaista", new String[]{"ulvais", "ulvas", });
    map.put ("vinkaista", new String[]{"vinkais", "vinkas", });
    map.put ("äyskäistä", new String[]{"äyskäis", "äyskäs", });
    map.put ("posmottaa", new String[]{"posmot", "posmoit", });
    map.put ("tytötellä", new String[]{"tytöt", "tytöit", });
    map.put ("vokottaa", new String[]{"vokot", "vokoit", });
    map.put ("losottaa", new String[]{"losot", "losoit", });
    map.put ("laidoittaa", new String[]{"laidoit", "laidot", });
    map.put ("nahoittaa", new String[]{"nahoit", "nahot", });
    map.put ("teemoittaa", new String[]{"teemoit", "teemot", });
    map.put ("järkevöittää", new String[]{"järkevöit", "järkevöt", });
    map.put ("tukevoittaa", new String[]{"tukevoit", "tukevot", });
    map.put ("jämäköittää", new String[]{"jämäköit", "jämäköt", });
    map.put ("sujuvoittaa", new String[]{"sujuvoit", "sujuvot", });
    map.put ("kyhjöttää", new String[]{"kyhjöt", "kyhjöit", });
    map.put ("jolkottaa", new String[]{"jolkot", "jolkoit", });
    map.put ("retkottaa", new String[]{"retkot", "retkoit", });
    map.put ("varsottaa", new String[]{"varsot", "varsoit", });
    map.put ("pannoittaa", new String[]{"pannoit", "pannot", });
    map.put ("silloittaa", new String[]{"silloit", "sillot", });
    map.put ("hölkötellä", new String[]{"hölköt", "hölköit", });
    map.put ("polisi", new String[]{"poliis", "polis"});
    map.put ("poliisi", new String[]{"polis", "poliis"});
    map.put ("kimnaasi", new String[]{"kymnaas", "kimnaas"});
    map.put ("kymnaasi", new String[]{"kimnaas", "kymnaas"});
  };
}
