/*
Copyright (©) 2021, 2024 Hannu Väisänen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


package peltomaa.sukija.suggestion.ahocorasick;

import org.ahocorasick.interval.*;
import org.ahocorasick.trie.*;
import org.ahocorasick.trie.handler.*;


class PayloadTrieClass {
  private static final PayloadTrie.PayloadTrieBuilder<String[]> payloadBuilder = PayloadTrie.<String[]>builder().ignoreOverlaps();
  private static final PayloadTrie<String[]> payloadTrie;

  private PayloadTrieClass() {}

  public static final PayloadTrie<String[]> getPayloadTrie() {return payloadTrie;}

  static {
    payloadBuilder.addKeyword ("absorptio", new String[]{"absorptio", "absorptsio", "absorptsioni", "absorptsiooni", });
    payloadBuilder.addKeyword ("abstraktio", new String[]{"abstraktio", "abstraktsio", "abstraktsioni", "abstraktsiooni", });
    payloadBuilder.addKeyword ("adaptaatio", new String[]{"adaptaatio", "adaptatio", "adaptatsioni", "adaptatsiooni", });
    payloadBuilder.addKeyword ("adoptio", new String[]{"adoptio", "adoptsio", "adoptsioni", "adoptsiooni", });
    payloadBuilder.addKeyword ("adpositio", new String[]{"adpositio", "adpositsio", "adpositsioni", "adpositsiooni", });
    payloadBuilder.addKeyword ("agitaatio", new String[]{"agitaatio", "agitatio", "agitatsioni", "agitatsiooni", });
    payloadBuilder.addKeyword ("aktio", new String[]{"aktio", "aktsio", "aktsioni", "aktsiooni", });
    payloadBuilder.addKeyword ("akupunktio", new String[]{"akupunktio", "akupunktsio", "akupunktsioni", "akupunktsiooni", });
    payloadBuilder.addKeyword ("allokaatio", new String[]{"allokaatio", "allokatio", "allokatsioni", "allokatsiooni", });
    payloadBuilder.addKeyword ("ambitio", new String[]{"ambitio", "ambitsio", "ambitsioni", "ambitsiooni", });
    payloadBuilder.addKeyword ("amputaatio", new String[]{"amputaatio", "amputatio", "amputatsioni", "amputatsiooni", });
    payloadBuilder.addKeyword ("animaatio", new String[]{"animaatio", "animatio", "animatsioni", "animatsiooni", });
    payloadBuilder.addKeyword ("appositio", new String[]{"appositio", "appositsio", "appositsioni", "appositsiooni", });
    payloadBuilder.addKeyword ("argumentaatio", new String[]{"argumentaatio", "argumentatio", "argumentatsioni", "argumentatsiooni", });
    payloadBuilder.addKeyword ("artikulaatio", new String[]{"artikulaatio", "artikulatio", "artikulatsioni", "artikulatsiooni", });
    payloadBuilder.addKeyword ("assimilaatio", new String[]{"assimilaatio", "assimilatio", "assimilatsioni", "assimilatsiooni", });
    payloadBuilder.addKeyword ("assosiaatio", new String[]{"assosiaatio", "assosiatio", "assosiatsioni", "assosiatsiooni", });
    payloadBuilder.addKeyword ("automaatio", new String[]{"automaatio", "automatio", "automatsioni", "automatsiooni", });
    payloadBuilder.addKeyword ("deduktio", new String[]{"deduktio", "deduktsio", "deduktsioni", "deduktsiooni", });
    payloadBuilder.addKeyword ("deflaatio", new String[]{"deflaatio", "deflatio", "deflatsioni", "deflatsiooni", });
    payloadBuilder.addKeyword ("deformaatio", new String[]{"deformaatio", "deformatio", "deformatsioni", "deformatsiooni", });
    payloadBuilder.addKeyword ("defreskaatio", new String[]{"defreskaatio", "defreskatio", "defreskatsioni", "defreskatsiooni", });
    payloadBuilder.addKeyword ("degeneraatio", new String[]{"degeneraatio", "degeneratio", "degeneratsioni", "degeneratsiooni", });
    payloadBuilder.addKeyword ("deklinaatio", new String[]{"deklinaatio", "deklinatio", "deklinatsioni", "deklinatsiooni", });
    payloadBuilder.addKeyword ("dekoraatio", new String[]{"dekoraatio", "dekoratio", "dekoratsioni", "dekoratsiooni", });
    payloadBuilder.addKeyword ("delegaatio", new String[]{"delegaatio", "delegatio", "delegatsioni", "delegatsiooni", });
    payloadBuilder.addKeyword ("delekaatio", new String[]{"delekaatio", "delekatio", "delekatsioni", "delekatsiooni", });
    payloadBuilder.addKeyword ("demarkaatio", new String[]{"demarkaatio", "demarkatio", "demarkatsioni", "demarkatsiooni", });
    payloadBuilder.addKeyword ("demonstraatio", new String[]{"demonstraatio", "demonstratio", "demonstratsioni", "demonstratsiooni", });
    payloadBuilder.addKeyword ("deskriptio", new String[]{"deskriptio", "deskriptsio", "deskriptsioni", "deskriptsiooni", });
    payloadBuilder.addKeyword ("devalvaatio", new String[]{"devalvaatio", "devalvatio", "devalvatsioni", "devalvatsiooni", });
    payloadBuilder.addKeyword ("disjunktio", new String[]{"disjunktio", "disjunktsio", "disjunktsioni", "disjunktsiooni", });
    payloadBuilder.addKeyword ("dispositio", new String[]{"dispositio", "dispositsio", "dispositsioni", "dispositsiooni", });
    payloadBuilder.addKeyword ("dokumentaatio", new String[]{"dokumentaatio", "dokumentatio", "dokumentatsioni", "dokumentatsiooni", });
    payloadBuilder.addKeyword ("editio", new String[]{"editio", "editsio", "editsioni", "editsiooni", });
    payloadBuilder.addKeyword ("elevaatio", new String[]{"elevaatio", "elevatio", "elevatsioni", "elevatsiooni", });
    payloadBuilder.addKeyword ("emansipaatio", new String[]{"emansipaatio", "emansipatio", "emansipatsioni", "emansipatsiooni", });
    payloadBuilder.addKeyword ("erektio", new String[]{"erektio", "erektsio", "erektsioni", "erektsiooni", });
    payloadBuilder.addKeyword ("estimaatio", new String[]{"estimaatio", "estimatio", "estimatsioni", "estimatsiooni", });
    payloadBuilder.addKeyword ("evaluaatio", new String[]{"evaluaatio", "evaluatio", "evaluatsioni", "evaluatsiooni", });
    payloadBuilder.addKeyword ("federaatio", new String[]{"federaatio", "federatio", "federatsioni", "federatsiooni", });
    payloadBuilder.addKeyword ("fiksaatio", new String[]{"fiksaatio", "fiksatio", "fiksatsioni", "fiksatsiooni", });
    payloadBuilder.addKeyword ("fiktio", new String[]{"fiktio", "fiktsio", "fiktsioni", "fiktsiooni", });
    payloadBuilder.addKeyword ("frustraatio", new String[]{"frustraatio", "frustratio", "frustratsioni", "frustratsiooni", });
    payloadBuilder.addKeyword ("funktio", new String[]{"funktio", "funktsio", "funktsioni", "funktsiooni", });
    payloadBuilder.addKeyword ("geminaatio", new String[]{"geminaatio", "geminatio", "geminatsioni", "geminatsiooni", });
    payloadBuilder.addKeyword ("globalisaatio", new String[]{"globalisaatio", "globalisatio", "globalisatsioni", "globalisatsiooni", });
    payloadBuilder.addKeyword ("gravitaatio", new String[]{"gravitaatio", "gravitatio", "gravitatsioni", "gravitatsiooni", });
    payloadBuilder.addKeyword ("hallusinaatio", new String[]{"hallusinaatio", "hallusinatio", "hallusinatsioni", "hallusinatsiooni", });
    payloadBuilder.addKeyword ("imitaatio", new String[]{"imitaatio", "imitatio", "imitatsioni", "imitatsiooni", });
    payloadBuilder.addKeyword ("improvisaatio", new String[]{"improvisaatio", "improvisatio", "improvisatsioni", "improvisatsiooni", });
    payloadBuilder.addKeyword ("indikaatio", new String[]{"indikaatio", "indikatio", "indikatsioni", "indikatsiooni", });
    payloadBuilder.addKeyword ("induktio", new String[]{"induktio", "induktsio", "induktsioni", "induktsiooni", });
    payloadBuilder.addKeyword ("infektio", new String[]{"infektio", "infektsio", "infektsioni", "infektsiooni", });
    payloadBuilder.addKeyword ("inflaatio", new String[]{"inflaatio", "inflatio", "inflatsioni", "inflatsiooni", });
    payloadBuilder.addKeyword ("informaatio", new String[]{"informaatio", "informatio", "informatsioni", "informatsiooni", });
    payloadBuilder.addKeyword ("inhalaatio", new String[]{"inhalaatio", "inhalatio", "inhalatsioni", "inhalatsiooni", });
    payloadBuilder.addKeyword ("initiaatio", new String[]{"initiaatio", "initiatio", "initiatsioni", "initiatsiooni", });
    payloadBuilder.addKeyword ("injektio", new String[]{"injektio", "injektsio", "injektsioni", "injektsiooni", });
    payloadBuilder.addKeyword ("inkarnaatio", new String[]{"inkarnaatio", "inkarnatio", "inkarnatsioni", "inkarnatsiooni", });
    payloadBuilder.addKeyword ("inkvisitio", new String[]{"inkvisitio", "inkvisitsio", "inkvisitsioni", "inkvisitsiooni", });
    payloadBuilder.addKeyword ("innovaatio", new String[]{"innovaatio", "innovatio", "innovatsioni", "innovatsiooni", });
    payloadBuilder.addKeyword ("inspiraatio", new String[]{"inspiraatio", "inspiratio", "inspiratsioni", "inspiratsiooni", });
    payloadBuilder.addKeyword ("integraatio", new String[]{"integraatio", "integratio", "integratsioni", "integratsiooni", });
    payloadBuilder.addKeyword ("interjektio", new String[]{"interjektio", "interjektsio", "interjektsioni", "interjektsiooni", });
    payloadBuilder.addKeyword ("interpolaatio", new String[]{"interpolaatio", "interpolatio", "interpolatsioni", "interpolatsiooni", });
    payloadBuilder.addKeyword ("intonaatio", new String[]{"intonaatio", "intonatio", "intonatsioni", "intonatsiooni", });
    payloadBuilder.addKeyword ("intuitio", new String[]{"intuitio", "intuitsio", "intuitsioni", "intuitsiooni", });
    payloadBuilder.addKeyword ("isolaatio", new String[]{"isolaatio", "isolatio", "isolatsioni", "isolatsiooni", });
    payloadBuilder.addKeyword ("iteraatio", new String[]{"iteraatio", "iteratio", "iteratsioni", "iteratsiooni", });
    payloadBuilder.addKeyword ("kastraatio", new String[]{"kastraatio", "kastratio", "kastratsioni", "kastratsiooni", });
//    payloadBuilder.addKeyword ("kirjoitin", new String[]{"kirjoit", "kirjot", });
    payloadBuilder.addKeyword ("koalitio", new String[]{"koalitio", "koalitsio", "koalitsioni", "koalitsiooni", });
    payloadBuilder.addKeyword ("kodifikaatio", new String[]{"kodifikaatio", "kodifikatio", "kodifikatsioni", "kodifikatsiooni", });
    payloadBuilder.addKeyword ("kognitio", new String[]{"kognitio", "kognitsio", "kognitsioni", "kognitsiooni", });
    payloadBuilder.addKeyword ("kombinaatio", new String[]{"kombinaatio", "kombinatio", "kombinatsioni", "kombinatsiooni", });
    payloadBuilder.addKeyword ("kommunikaatio", new String[]{"kommunikaatio", "kommunikatio", "kommunikatsioni", "kommunikatsiooni", });
    payloadBuilder.addKeyword ("komparaatio", new String[]{"komparaatio", "komparatio", "komparatsioni", "komparatsiooni", });
    payloadBuilder.addKeyword ("kompensaatio", new String[]{"kompensaatio", "kompensatio", "kompensatsioni", "kompensatsiooni", });
    payloadBuilder.addKeyword ("komplikaatio", new String[]{"komplikaatio", "komplikatio", "komplikatsioni", "komplikatsiooni", });
    payloadBuilder.addKeyword ("kompositio", new String[]{"kompositio", "kompositsio", "kompositsioni", "kompositsiooni", });
    payloadBuilder.addKeyword ("kondensaatio", new String[]{"kondensaatio", "kondensatio", "kondensatsioni", "kondensatsiooni", });
    payloadBuilder.addKeyword ("konditio", new String[]{"konditio", "konditsio", "konditsioni", "konditsiooni", });
    payloadBuilder.addKeyword ("konfiguraatio", new String[]{"konfiguraatio", "konfiguratio", "konfiguratsioni", "konfiguratsiooni", });
    payloadBuilder.addKeyword ("konfirmaatio", new String[]{"konfirmaatio", "konfirmatio", "konfirmatsioni", "konfirmatsiooni", });
    payloadBuilder.addKeyword ("konjugaatio", new String[]{"konjugaatio", "konjugatio", "konjugatsioni", "konjugatsiooni", });
    payloadBuilder.addKeyword ("konjunktio", new String[]{"konjunktio", "konjunktsio", "konjunktsioni", "konjunktsiooni", });
    payloadBuilder.addKeyword ("konnotaatio", new String[]{"konnotaatio", "konnotatio", "konnotatsioni", "konnotatsiooni", });
    payloadBuilder.addKeyword ("konstruktio", new String[]{"konstruktio", "konstruktsio", "konstruktsioni", "konstruktsiooni", });
    payloadBuilder.addKeyword ("konsultaatio", new String[]{"konsultaatio", "konsultatio", "konsultatsioni", "konsultatsiooni", });
    payloadBuilder.addKeyword ("kooperaatio", new String[]{"kooperaatio", "kooperatio", "kooperatsioni", "kooperatsiooni", });
    payloadBuilder.addKeyword ("koordinaatio", new String[]{"koordinaatio", "koordinatio", "koordinatsioni", "koordinatsiooni", });
    payloadBuilder.addKeyword ("korporaatio", new String[]{"korporaatio", "korporatio", "korporatsioni", "korporatsiooni", });
    payloadBuilder.addKeyword ("korrelaatio", new String[]{"korrelaatio", "korrelatio", "korrelatsioni", "korrelatsiooni", });
    payloadBuilder.addKeyword ("korruptio", new String[]{"korruptio", "korruptsio", "korruptsioni", "korruptsiooni", });
    payloadBuilder.addKeyword ("kulminaatio", new String[]{"kulminaatio", "kulminatio", "kulminatsioni", "kulminatsiooni", });
    payloadBuilder.addKeyword ("kumulaatio", new String[]{"kumulaatio", "kumulatio", "kumulatsioni", "kumulatsiooni", });
    payloadBuilder.addKeyword ("kvalifikaatio", new String[]{"kvalifikaatio", "kvalifikatio", "kvalifikatsioni", "kvalifikatsiooni", });
    payloadBuilder.addKeyword ("levitaatio", new String[]{"levitaatio", "levitatio", "levitatsioni", "levitatsiooni", });
    payloadBuilder.addKeyword ("lokalisaatio", new String[]{"lokalisaatio", "lokalisatio", "lokalisatsioni", "lokalisatsiooni", });
    payloadBuilder.addKeyword ("manipulaatio", new String[]{"manipulaatio", "manipulatio", "manipulatsioni", "manipulatsiooni", });
    payloadBuilder.addKeyword ("masturbaatio", new String[]{"masturbaatio", "masturbatio", "masturbatsioni", "masturbatsiooni", });
    payloadBuilder.addKeyword ("materialisaatio", new String[]{"materialisaatio", "materialisatio", "materialisatsioni", "materialisatsiooni", });
    payloadBuilder.addKeyword ("meditaatio", new String[]{"meditaatio", "meditatio", "meditatsioni", "meditatsiooni", });
    payloadBuilder.addKeyword ("menstruaatio", new String[]{"menstruaatio", "menstruatio", "menstruatsioni", "menstruatsiooni", });
    payloadBuilder.addKeyword ("migraatio", new String[]{"migraatio", "migratio", "migratsioni", "migratsiooni", });
    payloadBuilder.addKeyword ("mobilisaatio", new String[]{"mobilisaatio", "mobilisatio", "mobilisatsioni", "mobilisatsiooni", });
    payloadBuilder.addKeyword ("modifikaatio", new String[]{"modifikaatio", "modifikatio", "modifikatsioni", "modifikatsiooni", });
    payloadBuilder.addKeyword ("modulaatio", new String[]{"modulaatio", "modulatio", "modulatsioni", "modulatsiooni", });
    payloadBuilder.addKeyword ("motivaatio", new String[]{"motivaatio", "motivatio", "motivatsioni", "motivatsiooni", });
    payloadBuilder.addKeyword ("mutaatio", new String[]{"mutaatio", "mutatio", "mutatsioni", "mutatsiooni", });
    payloadBuilder.addKeyword ("mystifikaatio", new String[]{"mystifikaatio", "mystifikatio", "mystifikatsioni", "mystifikatsiooni", });
    payloadBuilder.addKeyword ("navigaatio", new String[]{"navigaatio", "navigatio", "navigatsioni", "navigatsiooni", });
    payloadBuilder.addKeyword ("negaatio", new String[]{"negaatio", "negatio", "negatsioni", "negatsiooni", });
    payloadBuilder.addKeyword ("neutralisaatio", new String[]{"neutralisaatio", "neutralisatio", "neutralisatsioni", "neutralisatsiooni", });
    payloadBuilder.addKeyword ("normalisaatio", new String[]{"normalisaatio", "normalisatio", "normalisatsioni", "normalisatsiooni", });
    payloadBuilder.addKeyword ("notaatio", new String[]{"notaatio", "notatio", "notatsioni", "notatsiooni", });
    payloadBuilder.addKeyword ("nutaatio", new String[]{"nutaatio", "nutatio", "nutatsioni", "nutatsiooni", });
    payloadBuilder.addKeyword ("obligaatio", new String[]{"obligaatio", "obligatio", "obligatsioni", "obligatsiooni", });
    payloadBuilder.addKeyword ("operaatio", new String[]{"operaatio", "operatio", "operatsioni", "operatsiooni", });
    payloadBuilder.addKeyword ("oppositio", new String[]{"oppositio", "oppositsio", "oppositsioni", "oppositsiooni", });
//    payloadBuilder.addKeyword ("optio", new String[]{"optio", "optsio", "optsioni", "optsiooni", });
    payloadBuilder.addKeyword ("organisaatio", new String[]{"organisaatio", "organisatio", "organisatsioni", "organisatsiooni", });
    payloadBuilder.addKeyword ("orientaatio", new String[]{"orientaatio", "orientatio", "orientatsioni", "orientatsiooni", });
    payloadBuilder.addKeyword ("oskillaatio", new String[]{"oskillaatio", "oskillatio", "oskillatsioni", "oskillatsiooni", });
//    payloadBuilder.addKeyword ("osoitin", new String[]{"osoit", "osot", });
    payloadBuilder.addKeyword ("ovulaatio", new String[]{"ovulaatio", "ovulatio", "ovulatsioni", "ovulatsiooni", });
    payloadBuilder.addKeyword ("partitio", new String[]{"partitio", "partitsio", "partitsioni", "partitsiooni", });
    payloadBuilder.addKeyword ("personifikaatio", new String[]{"personifikaatio", "personifikatio", "personifikatsioni", "personifikatsiooni", });
    payloadBuilder.addKeyword ("polarisaatio", new String[]{"polarisaatio", "polarisatio", "polarisatsioni", "polarisatsiooni", });
    payloadBuilder.addKeyword ("populaatio", new String[]{"populaatio", "populatio", "populatsioni", "populatsiooni", });
    payloadBuilder.addKeyword ("positio", new String[]{"positio", "positsio", "positsioni", "positsiooni", });
    payloadBuilder.addKeyword ("postpositio", new String[]{"postpositio", "postpositsio", "postpositsioni", "postpositsiooni", });
    payloadBuilder.addKeyword ("predestinaatio", new String[]{"predestinaatio", "predestinatio", "predestinatsioni", "predestinatsiooni", });
    payloadBuilder.addKeyword ("prepositio", new String[]{"prepositio", "prepositsio", "prepositsioni", "prepositsiooni", });
    payloadBuilder.addKeyword ("produktio", new String[]{"produktio", "produktsio", "produktsioni", "produktsiooni", });
    payloadBuilder.addKeyword ("projektio", new String[]{"projektio", "projektsio", "projektsioni", "projektsiooni", });
    payloadBuilder.addKeyword ("propagaatio", new String[]{"propagaatio", "propagatio", "propagatsioni", "propagatsiooni", });
    payloadBuilder.addKeyword ("propositio", new String[]{"propositio", "propositsio", "propositsioni", "propositsiooni", });
    payloadBuilder.addKeyword ("provisio", new String[]{"provisio", "provisioni", "provisiooni", });
    payloadBuilder.addKeyword ("provokaatio", new String[]{"provokaatio", "provokatio", "provokatsioni", "provokatsiooni", });
    payloadBuilder.addKeyword ("punktio", new String[]{"punktio", "punktsio", "punktsioni", "punktsiooni", });
//    payloadBuilder.addKeyword ("rajoitin", new String[]{"rajoit", "rajot", });
    payloadBuilder.addKeyword ("reaktio", new String[]{"reaktio", "reaktsio", "reaktsioni", "reaktsiooni", });
    payloadBuilder.addKeyword ("realisaatio", new String[]{"realisaatio", "realisatio", "realisatsioni", "realisatsiooni", });
    payloadBuilder.addKeyword ("reduktio", new String[]{"reduktio", "reduktsio", "reduktsioni", "reduktsiooni", });
    payloadBuilder.addKeyword ("reformaatio", new String[]{"reformaatio", "reformatio", "reformatsioni", "reformatsiooni", });
    payloadBuilder.addKeyword ("rehabilitaatio", new String[]{"rehabilitaatio", "rehabilitatio", "rehabilitatsioni", "rehabilitatsiooni", });
    payloadBuilder.addKeyword ("reklamaatio", new String[]{"reklamaatio", "reklamatio", "reklamatsioni", "reklamatsiooni", });
    payloadBuilder.addKeyword ("rektio", new String[]{"rektio", "rektsio", "rektsioni", "rektsiooni", });
    payloadBuilder.addKeyword ("relaatio", new String[]{"relaatio", "relatio", "relatsioni", "relatsiooni", });
    payloadBuilder.addKeyword ("restauraatio", new String[]{"restauraatio", "restauratio", "restauratsioni", "restauratsiooni", });
    payloadBuilder.addKeyword ("revalvaatio", new String[]{"revalvaatio", "revalvatio", "revalvatsioni", "revalvatsiooni", });
    payloadBuilder.addKeyword ("rotaatio", new String[]{"rotaatio", "rotatio", "rotatsioni", "rotatsiooni", });
    payloadBuilder.addKeyword ("sanktio", new String[]{"sanktio", "sanktsio", "sanktsioni", "sanktsiooni", });
    payloadBuilder.addKeyword ("segregaatio", new String[]{"segregaatio", "segregatio", "segregatsioni", "segregatsiooni", });
//    payloadBuilder.addKeyword ("sekoitin", new String[]{"sekoit", "sekot", });
    payloadBuilder.addKeyword ("sektio", new String[]{"sektio", "sektsio", "sektsioni", "sektsiooni", });
    payloadBuilder.addKeyword ("sensaatio", new String[]{"sensaatio", "sensatio", "sensatsioni", "sensatsiooni", });
    payloadBuilder.addKeyword ("sentralisaatio", new String[]{"sentralisaatio", "sentralisatio", "sentralisatsioni", "sentralisatsiooni", });
    payloadBuilder.addKeyword ("sivilisaatio", new String[]{"sivilisaatio", "sivilisatio", "sivilisatsioni", "sivilisatsiooni", });
    payloadBuilder.addKeyword ("sosialisaatio", new String[]{"sosialisaatio", "sosialisatio", "sosialisatsioni", "sosialisatsiooni", });
    payloadBuilder.addKeyword ("spekulaatio", new String[]{"spekulaatio", "spekulatio", "spekulatsioni", "spekulatsiooni", });
    payloadBuilder.addKeyword ("spesifikaatio", new String[]{"spesifikaatio", "spesifikatio", "spesifikatsioni", "spesifikatsiooni", });
    payloadBuilder.addKeyword ("stagnaatio", new String[]{"stagnaatio", "stagnatio", "stagnatsioni", "stagnatsiooni", });
    payloadBuilder.addKeyword ("sterilisaatio", new String[]{"sterilisaatio", "sterilisatio", "sterilisatsioni", "sterilisatsiooni", });
//    payloadBuilder.addKeyword ("teroitin", new String[]{"teroit", "terot", });
    payloadBuilder.addKeyword ("topikalisaatio", new String[]{"topikalisaatio", "topikalisatio", "topikalisatsioni", "topikalisatsiooni", });
    payloadBuilder.addKeyword ("traditio", new String[]{"traditio", "traditsio", "traditsioni", "traditsiooni", });
    payloadBuilder.addKeyword ("transformaatio", new String[]{"transformaatio", "transformatio", "transformatsioni", "transformatsiooni", });
    payloadBuilder.addKeyword ("translaatio", new String[]{"translaatio", "translatio", "translatsioni", "translatsiooni", });
    payloadBuilder.addKeyword ("undulaatio", new String[]{"undulaatio", "undulatio", "undulatsioni", "undulatsiooni", });
    payloadBuilder.addKeyword ("variaatio", new String[]{"variaatio", "variatio", "variatsioni", "variatsiooni", });
    payloadBuilder.addKeyword ("ventilaatio", new String[]{"ventilaatio", "ventilatio", "ventilatsioni", "ventilatsiooni", });
    payloadBuilder.addKeyword ("verifikaatio", new String[]{"verifikaatio", "verifikatio", "verifikatsioni", "verifikatsiooni", });
//    payloadBuilder.addKeyword ("viivoitin", new String[]{"viivoit", "viivot", });
    payloadBuilder.addKeyword ("somatisaatio", new String[]{"somatisaatio", "somatisatio", "somatisatsioni", "somatisatsiooni", });
    payloadBuilder.addKeyword ("stimulaatio", new String[]{"stimulaatio", "stimulatio", "stimulatsioni", "stimulatsiooni", });
    payloadBuilder.addKeyword ("saturaatio", new String[]{"saturaatio", "saturatio", "saturatsioni", "saturatsiooni", });
    payloadBuilder.addKeyword ("permutaatio", new String[]{"permutaatio", "permutatio", "permutatsioni", "permutatsiooni", });
    payloadBuilder.addKeyword ("bijektio", new String[]{"bijektio", "bijektsio", "bijektsioni", "bijektsiooni", });
    payloadBuilder.addKeyword ("surjektio", new String[]{"surjektio", "surjektsio", "surjektsioni", "surjektsiooni", });
    payloadBuilder.addKeyword ("prekarisaatio", new String[]{"prekarisaatio", "prekarisatio", "prekarisatsioni", "prekarisatsiooni", });
    payloadBuilder.addKeyword ("indoktrinaatio", new String[]{"indoktrinaatio", "indoktrinatio", "indoktrinatsioni", "indoktrinatsiooni", });
    payloadBuilder.addKeyword ("akkommodaatio", new String[]{"akkommodaatio", "akkommodatio", "akkommodatsioni", "akkommodatsiooni", });
    payloadBuilder.addKeyword ("abduktio", new String[]{"abduktio", "abduktsio", "abduktsioni", "abduktsiooni", });
    payloadBuilder.addKeyword ("aktivaatio", new String[]{"aktivaatio", "aktivatio", "aktivatsioni", "aktivatsiooni", });
    payloadBuilder.addKeyword ("auskultaatio", new String[]{"auskultaatio", "auskultatio", "auskultatsioni", "auskultatsiooni", });
    payloadBuilder.addKeyword ("falsifikaatio", new String[]{"falsifikaatio", "falsifikatio", "falsifikatsioni", "falsifikatsiooni", });
    payloadBuilder.addKeyword ("diffraktio", new String[]{"diffraktio", "diffraktsio", "diffraktsioni", "diffraktsiooni", });
    payloadBuilder.addKeyword ("teleportaatio", new String[]{"teleportaatio", "teleportatio", "teleportatsioni", "teleportatsiooni", });
    payloadBuilder.addKeyword ("reflektio", new String[]{"reflektio", "reflektsio", "reflektsioni", "reflektsiooni", });
    payloadBuilder.addKeyword ("individualisaatio", new String[]{"individualisaatio", "individualisatio", "individualisatsioni", "individualisatsiooni", });
    payloadBuilder.addKeyword ("fellaatio", new String[]{"fellaatio", "fellatio", "fellatsioni", "fellatsiooni", });
    payloadBuilder.addKeyword ("ejakulaatio", new String[]{"ejakulaatio", "ejakulatio", "ejakulatsioni", "ejakulatsiooni", });
    payloadBuilder.addKeyword ("simulaatio", new String[]{"simulaatio", "simulatio", "simulatsioni", "simulatsiooni", });
    payloadBuilder.addKeyword ("kontradiktio", new String[]{"kontradiktio", "kontradiktsio", "kontradiktsioni", "kontradiktsiooni", });
    payloadBuilder.addKeyword ("kausaatio", new String[]{"kausaatio", "kausatio", "kausatsioni", "kausatsiooni", });
    payloadBuilder.addKeyword ("emulaatio", new String[]{"emulaatio", "emulatio", "emulatsioni", "emulatsiooni", });
    payloadBuilder.addKeyword ("distinktio", new String[]{"distinktio", "distinktsio", "distinktsioni", "distinktsiooni", });
    payloadBuilder.addKeyword ("predikaatio", new String[]{"predikaatio", "predikatio", "predikatsioni", "predikatsiooni", });
    payloadBuilder.addKeyword ("denotaatio", new String[]{"denotaatio", "denotatio", "denotatsioni", "denotatsiooni", });
    payloadBuilder.addKeyword ("addiktio", new String[]{"addiktio", "addiktsio", "addiktsioni", "addiktsiooni", });
    payloadBuilder.addKeyword ("deviaatio", new String[]{"deviaatio", "deviatio", "deviatsioni", "deviatsiooni", });
    payloadBuilder.addKeyword ("identifikaatio", new String[]{"identifikaatio", "identifikatio", "identifikatsioni", "identifikatsiooni", });
    payloadBuilder.addKeyword ("transkriptio", new String[]{"transkriptio", "transkriptsio", "transkriptsioni", "transkriptsiooni", });
    payloadBuilder.addKeyword ("installaatio", new String[]{"installaatio", "installatio", "installatsioni", "installatsiooni", });
    payloadBuilder.addKeyword ("ionisaatio", new String[]{"ionisaatio", "ionisatio", "ionisatsioni", "ionisatsiooni", });
    payloadBuilder.addKeyword ("vivisektio", new String[]{"vivisektio", "vivisektsio", "vivisektsioni", "vivisektsiooni", });
    payloadBuilder.addKeyword ("immunisaatio", new String[]{"immunisaatio", "immunisatio", "immunisatsioni", "immunisatsiooni", });
//    payloadBuilder.addKeyword ("ilmoitin", new String[]{"ilmoit", "ilmot", });
    payloadBuilder.addKeyword ("regeneraatio", new String[]{"regeneraatio", "regeneratio", "regeneratsioni", "regeneratsiooni", });
    payloadBuilder.addKeyword ("resignaatio", new String[]{"resignaatio", "resignatio", "resignatsioni", "resignatsiooni", });
    payloadBuilder.addKeyword ("fraktio", new String[]{"fraktio", "fraktsio", "fraktsioni", "fraktsiooni", });
    payloadBuilder.addKeyword ("kavitaatio", new String[]{"kavitaatio", "kavitatio", "kavitatsioni", "kavitatsiooni", });
    payloadBuilder.addKeyword ("redaktio", new String[]{"redaktio", "redaktsio", "redaktsioni", "redaktsiooni", });
    payloadBuilder.addKeyword ("implementaatio", new String[]{"implementaatio", "implementatio", "implementatsioni", "implementatsiooni", });
    payloadBuilder.addKeyword ("refraktio", new String[]{"refraktio", "refraktsio", "refraktsioni", "refraktsiooni", });
    payloadBuilder.addKeyword ("regulaatio", new String[]{"regulaatio", "regulatio", "regulatsioni", "regulatsiooni", });
    payloadBuilder.addKeyword ("kristallisaatio", new String[]{"kristallisaatio", "kristallisatio", "kristallisatsioni", "kristallisatsiooni", });
    payloadBuilder.addKeyword ("subduktio", new String[]{"subduktio", "subduktsio", "subduktsioni", "subduktsiooni", });
    payloadBuilder.addKeyword ("sublimaatio", new String[]{"sublimaatio", "sublimatio", "sublimatsioni", "sublimatsiooni", });
    payloadBuilder.addKeyword ("situaatio", new String[]{"situaatio", "situatio", "situatstioni", "situaatsioni", });
    payloadBuilder.addKeyword ("penetraatio", new String[]{"penetraatio", "penetratio", "penetratsioni", "penetratsiooni", });
    payloadBuilder.addKeyword ("mekanisaatio", new String[]{"mekanisaatio", "mekanisatio", "mekanisatsioni", "mekanisatsiooni", });
    payloadBuilder.addKeyword ("sekularisaatio", new String[]{"sekularisaatio", "sekularisatio", "sekularisatsioni", "sekularisatsiooni", });
    payloadBuilder.addKeyword ("aberraatio", new String[]{"aberraatio", "aberratio", "aberratsioni", "aberratsiooni", });
    payloadBuilder.addKeyword ("ablaatio", new String[]{"ablaatio", "ablatio", "ablatsioni", "ablatsiooni", });
//    payloadBuilder.addKeyword ("varoitin", new String[]{"varoit", "varot", });
//    payloadBuilder.addKeyword ("hiekoitin", new String[]{"hiekoit", "hiekot", });
//    payloadBuilder.addKeyword ("kartoitin", new String[]{"kartoit", "kartot", });
//    payloadBuilder.addKeyword ("lannoitin", new String[]{"lannoit", "lannot", });
//    payloadBuilder.addKeyword ("tasoitin", new String[]{"tasoit", "tasot", });
//    payloadBuilder.addKeyword ("virroitin", new String[]{"virroit", "virrot", });
    payloadBuilder.addKeyword ("additio", new String[]{"additio", "additsio", "additsioni", "additsiooni", });
    payloadBuilder.addKeyword ("adsorptio", new String[]{"adsorptio", "adsorptsio", "adsorptsioni", "adsorptsiooni", });
    payloadBuilder.addKeyword ("advektio", new String[]{"advektio", "advektsio", "advektsioni", "advektsiooni", });
    payloadBuilder.addKeyword ("eliminaatio", new String[]{"eliminaatio", "eliminatio", "eliminatsioni", "eliminatsiooni", });
    payloadBuilder.addKeyword ("ekskommunikaatio", new String[]{"ekskommunikaatio", "ekskommunikatio", "ekskommunikatsioni", "ekskommunikatsiooni", });
    payloadBuilder.addKeyword ("vietnamisaatio", new String[]{"vietnamisaatio", "vietnamisatio", "vietnamisatsioni", "vietnamisatsiooni", });
    payloadBuilder.addKeyword ("deklamaatio", new String[]{"deklamaatio", "deklamatio", "deklamatsioni", "deklamatsiooni", });
    payloadBuilder.addKeyword ("inkubaatio", new String[]{"inkubaatio", "inkubatio", "inkubatsioni", "inkubatsiooni", });
    payloadBuilder.addKeyword ("mineralisaatio", new String[]{"mineralisaatio", "mineralisatio", "mineralisatsioni", "mineralisatsiooni", });
    payloadBuilder.addKeyword ("replikaatio", new String[]{"replikaatio", "replikatio", "replikatsioni", "replikatsiooni", });
    payloadBuilder.addKeyword ("perforaatio", new String[]{"perforaatio", "perforatio", "perforatsioni", "perforatsiooni", });
    payloadBuilder.addKeyword ("konsentraatio", new String[]{"konsentraatio", "konsentratio", "konsentratsioni", "konsentratsiooni", });
    payloadBuilder.addKeyword ("akkumulaatio", new String[]{"akkumulaatio", "akkumulatio", "akkumulatsioni", "akkumulatsiooni", });
    payloadBuilder.addKeyword ("konformaatio", new String[]{"konformaatio", "konformatio", "konformatsioni", "konformatsiooni", });
    payloadBuilder.addKeyword ("litteraatio", new String[]{"litteraatio", "litteratio", "litteratsioni", "litteratsiooni", });
    payloadBuilder.addKeyword ("konvektio", new String[]{"konvektio", "konvektsio", "konvektsioni", "konvektsiooni", });
    payloadBuilder.addKeyword ("reduplikaatio", new String[]{"reduplikaatio", "reduplikatio", "reduplikatsioni", "reduplikatsiooni", });
    payloadBuilder.addKeyword ("urbanisaatio", new String[]{"urbanisaatio", "urbanisatio", "urbanisatsioni", "urbanisatsiooni", });
    payloadBuilder.addKeyword ("illustraatio", new String[]{"illustraatio", "illustratio", "illustratsioni", "illustratsiooni", });
    payloadBuilder.addKeyword ("implantaatio", new String[]{"implantaatio", "implantatio", "implantatsioni", "implantatsiooni", });
    payloadBuilder.addKeyword ("inhibitio", new String[]{"inhibitio", "inhibitsio", "inhibitsioni", "inhibitsiooni", });
    payloadBuilder.addKeyword ("fermentaatio", new String[]{"fermentaatio", "fermentatio", "fermentatsioni", "fermentatsiooni", });
    payloadBuilder.addKeyword ("fosforylaatio", new String[]{"fosforylaatio", "fosforylatio", "fosforylatsioni", "fosforylatsiooni", });
    payloadBuilder.addKeyword ("obstruktio", new String[]{"obstruktio", "obstruktsio", "obstruktsioni", "obstruktsiooni", });
    payloadBuilder.addKeyword ("relaksaatio", new String[]{"relaksaatio", "relaksatio", "relaksatsioni", "relaksatsiooni", });
    payloadBuilder.addKeyword ("polymerisaatio", new String[]{"polymerisaatio", "polymerisatio", "polymerisatsioni", "polymerisatsiooni", });
    payloadBuilder.addKeyword ("fokalisaatio", new String[]{"fokalisaatio", "fokalisatio", "fokalisatsioni", "fokalisatsiooni", });
    payloadBuilder.addKeyword ("glukuronidaatio", new String[]{"glukuronidaatio", "glukuronidatio", "glukuronidatsioni", "glukuronidatsiooni", });
    payloadBuilder.addKeyword ("medikalisaatio", new String[]{"medikalisaatio", "medikalisatio", "medikalisatsioni", "medikalisatsiooni", });
    payloadBuilder.addKeyword ("dislokaatio", new String[]{"dislokaatio", "dislokatio", "dislokatsioni", "dislokatsiooni", });
    payloadBuilder.addKeyword ("disputaatio", new String[]{"disputaatio", "disputatio", "disputatsioni", "disputatsiooni", });
    payloadBuilder.addKeyword ("dissosiaatio", new String[]{"dissosiaatio", "dissosiatio", "dissosiatsioni", "dissosiatsiooni", });
    payloadBuilder.addKeyword ("obduktio", new String[]{"obduktio", "obduktsio", "obduktsioni", "obduktsiooni", });
    payloadBuilder.addKeyword ("palpaatio", new String[]{"palpaatio", "palpatio", "palpatsioni", "palpatsiooni", });
    payloadBuilder.addKeyword ("luksaatio", new String[]{"luksaatio", "luksatio", "luksatsioni", "luksatsiooni", });
    payloadBuilder.addKeyword ("kolonisaatio", new String[]{"kolonisaatio", "kolonisatio", "kolonisatsioni", "kolonisatsiooni", });
    payloadBuilder.addKeyword ("personalisaatio", new String[]{"personalisaatio", "personalisatio", "personalisatsioni", "personalisatsiooni", });
    payloadBuilder.addKeyword ("militarisaatio", new String[]{"militarisaatio", "militarisatio", "militarisatsioni", "militarisatsiooni", });
    payloadBuilder.addKeyword ("hydraatio", new String[]{"hydraatio", "hydratio", "hydratsioni", "hydratsiooni", });
    payloadBuilder.addKeyword ("parametrisaatio", new String[]{"parametrisaatio", "parametrisatio", "parametrisatsioni", "parametrisatsiooni", });
    payloadBuilder.addKeyword ("visualisaatio", new String[]{"visualisaatio", "visualisatio", "visualisatsioni", "visualisatsiooni", });
    payloadBuilder.addKeyword ("idealisaatio", new String[]{"idealisaatio", "idealisatio", "idealisatsioni", "idealisatsiooni", });
    payloadBuilder.addKeyword ("adduktio", new String[]{"adduktio", "adduktsio", "adduktsioni", "adduktsiooni", });
    payloadBuilder.addKeyword ("resektio", new String[]{"resektio", "resektsio", "resektsioni", "resektsiooni", });
    payloadBuilder.addKeyword ("suturaatio", new String[]{"suturaatio", "suturatio", "suturatsioni", "suturatsiooni", });
    payloadBuilder.addKeyword ("aspiraatio", new String[]{"aspiraatio", "aspiratio", "aspiratsioni", "aspiratsiooni", });
    payloadBuilder.addKeyword ("inflammaatio", new String[]{"inflammaatio", "inflammatio", "inflammatsioni", "inflammatsiooni", });
    payloadBuilder.addKeyword ("intubaatio", new String[]{"intubaatio", "intubatio", "intubatsioni", "intubatsiooni", });
    payloadBuilder.addKeyword ("kontaminaatio", new String[]{"kontaminaatio", "kontaminatio", "kontaminatsioni", "kontaminatsiooni", });
    payloadBuilder.addKeyword ("intoksikaatio", new String[]{"intoksikaatio", "intoksikatio", "intoksikatsioni", "intoksikatsiooni", });
    payloadBuilder.addKeyword ("desorientaatio", new String[]{"desorientaatio", "desorientatio", "desorientatsioni", "desorientatsiooni", });
    payloadBuilder.addKeyword ("herniaatio", new String[]{"herniaatio", "herniatio", "herniatsioni", "herniatsiooni", });
    payloadBuilder.addKeyword ("sedaatio", new String[]{"sedaatio", "sedatio", "sedatsioni", "sedatsiooni", });
    payloadBuilder.addKeyword ("modernisaatio", new String[]{"modernisaatio", "modernisatio", "modernisatsioni", "modernisatsiooni", });
    payloadBuilder.addKeyword ("industrialisaatio", new String[]{"industrialisaatio", "industrialisatio", "industrialisatsioni", "industrialisatsiooni", });
    payloadBuilder.addKeyword ("konfederaatio", new String[]{"konfederaatio", "konfederatio", "konfederatsioni", "konfederatsiooni", });
    payloadBuilder.addKeyword ("granulaatio", new String[]{"granulaatio", "granulatio", "granulatsioni", "granulatsiooni", });
    payloadBuilder.addKeyword ("tamponaatio", new String[]{"tamponaatio", "tamponatio", "tamponatsioni", "tamponatsiooni", });
    payloadBuilder.addKeyword ("aggregaatio", new String[]{"aggregaatio", "aggregatio", "aggregatsioni", "aggregatsiooni", });
    payloadBuilder.addKeyword ("irritaatio", new String[]{"irritaatio", "irritatio", "irritatsioni", "irritatsiooni", });
    payloadBuilder.addKeyword ("pigmentaatio", new String[]{"pigmentaatio", "pigmentatio", "pigmentatsioni", "pigmentatsiooni", });
    payloadBuilder.addKeyword ("palpitaatio", new String[]{"palpitaatio", "palpitatio", "palpitatsioni", "palpitatsiooni", });
    payloadBuilder.addKeyword ("inspektio", new String[]{"inspektio", "inspektsio", "inspektsioni", "inspektsiooni", });
    payloadBuilder.addKeyword ("angulaatio", new String[]{"angulaatio", "angulatio", "angulatsioni", "angulatsiooni", });
    payloadBuilder.addKeyword ("dilataatio", new String[]{"dilataatio", "dilatatio", "dilatatsioni", "dilatatsiooni", });
    payloadBuilder.addKeyword ("koarktaatio", new String[]{"koarktaatio", "koarktatio", "koarktatsioni", "koarktatsiooni", });
    payloadBuilder.addKeyword ("proliferaatio", new String[]{"proliferaatio", "proliferatio", "proliferatsioni", "proliferatsiooni", });
    payloadBuilder.addKeyword ("resorptio", new String[]{"resorptio", "resorptsio", "resorptsioni", "resorptsiooni", });
    payloadBuilder.addKeyword ("eksitaatio", new String[]{"eksitaatio", "eksitatio", "eksitatsioni", "eksitatsiooni", });
    payloadBuilder.addKeyword ("kontraktio", new String[]{"kontraktio", "kontraktsio", "kontraktsioni", "kontraktsiooni", });
    payloadBuilder.addKeyword ("akkulturaatio", new String[]{"akkulturaatio", "akkulturatio", "akkulturatsioni", "akkulturatsiooni", });
    payloadBuilder.addKeyword ("restriktio", new String[]{"restriktio", "restriktsio", "restriktsioni", "restriktsiooni", });
    payloadBuilder.addKeyword ("kalibraatio", new String[]{"kalibraatio", "kalibratio", "kalibratsioni", "kalibratsiooni", });
    payloadBuilder.addKeyword ("augmentaatio", new String[]{"augmentaatio", "augmentatio", "augmentatsioni", "augmentatsiooni", });
    payloadBuilder.addKeyword ("faskikulaatio", new String[]{"faskikulaatio", "faskikulatio", "faskikulatsioni", "faskikulatsiooni", });
    payloadBuilder.addKeyword ("hydroksylaatio", new String[]{"hydroksylaatio", "hydroksylatio", "hydroksylatsioni", "hydroksylatsiooni", });
    payloadBuilder.addKeyword ("oksidaatio", new String[]{"oksidaatio", "oksidatio", "oksidatsioni", "oksidatsiooni", });
    payloadBuilder.addKeyword ("konstriktio", new String[]{"konstriktio", "konstriktsio", "konstriktsioni", "konstriktsiooni", });
    payloadBuilder.addKeyword ("salivaatio", new String[]{"salivaatio", "salivatio", "salivatsioni", "salivatsiooni", });
    payloadBuilder.addKeyword ("dissektio", new String[]{"dissektio", "dissektsio", "dissektsioni", "dissektsiooni", });
    payloadBuilder.addKeyword ("androgenisaatio", new String[]{"androgenisaatio", "androgenisatio", "androgenisatsioni", "androgenisatsiooni", });
    payloadBuilder.addKeyword ("applikaatio", new String[]{"applikaatio", "applikatio", "applikatsioni", "applikatsiooni", });
    payloadBuilder.addKeyword ("fibrillaatio", new String[]{"fibrillaatio", "fibrillatio", "fibrillatsioni", "fibrillatsiooni", });
    payloadBuilder.addKeyword ("ekstubaatio", new String[]{"ekstubaatio", "ekstubatio", "ekstubatsioni", "ekstubatsiooni", });
    payloadBuilder.addKeyword ("embolisaatio", new String[]{"embolisaatio", "embolisatio", "embolisatsioni", "embolisatsiooni", });
    payloadBuilder.addKeyword ("feminisaatio", new String[]{"feminisaatio", "feminisatio", "feminisatsioni", "feminisatsiooni", });
    payloadBuilder.addKeyword ("fertilisaatio", new String[]{"fertilisaatio", "fertilisatio", "fertilisatsioni", "fertilisatsiooni", });
    payloadBuilder.addKeyword ("filtraatio", new String[]{"filtraatio", "filtratio", "filtratsioni", "filtratsiooni", });
    payloadBuilder.addKeyword ("nitrifikaatio", new String[]{"nitrifikaatio", "nitrifikatio", "nitrifikatsioni", "nitrifikatsiooni", });
    payloadBuilder.addKeyword ("ekskoriaatio", new String[]{"ekskoriaatio", "ekskoriatio", "ekskoriatsioni", "ekskoriatsiooni", });
    payloadBuilder.addKeyword ("eradikaatio", new String[]{"eradikaatio", "eradikatio", "eradikatsioni", "eradikatsiooni", });
    payloadBuilder.addKeyword ("habituaatio", new String[]{"habituaatio", "habituatio", "habituatsioni", "habituatsiooni", });
    payloadBuilder.addKeyword ("instillaatio", new String[]{"instillaatio", "instillatio", "instillatsioni", "instillatsiooni", });
    payloadBuilder.addKeyword ("virilisaatio", new String[]{"virilisaatio", "virilisatio", "virilisatsioni", "virilisatsiooni", });
    payloadBuilder.addKeyword ("habilitaatio", new String[]{"habilitaatio", "habilitatio", "habilitatsioni", "habilitatsiooni", });
    payloadBuilder.addKeyword ("eksudaatio", new String[]{"eksudaatio", "eksudatio", "eksudatsioni", "eksudatsiooni", });
    payloadBuilder.addKeyword ("gestaatio", new String[]{"gestaatio", "gestatio", "gestatsioni", "gestatsiooni", });
    payloadBuilder.addKeyword ("induraatio", new String[]{"induraatio", "induratio", "induratsioni", "induratsiooni", });
    payloadBuilder.addKeyword ("infiltraatio", new String[]{"infiltraatio", "infiltratio", "infiltratsioni", "infiltratsiooni", });
    payloadBuilder.addKeyword ("kalsifikaatio", new String[]{"kalsifikaatio", "kalsifikatio", "kalsifikatsioni", "kalsifikatsiooni", });
    payloadBuilder.addKeyword ("konstipaatio", new String[]{"konstipaatio", "konstipatio", "konstipatsioni", "konstipatsiooni", });
    payloadBuilder.addKeyword ("lakrimaatio", new String[]{"lakrimaatio", "lakrimatio", "lakrimatsioni", "lakrimatsiooni", });
    payloadBuilder.addKeyword ("laktaatio", new String[]{"laktaatio", "laktatio", "laktatsioni", "laktatsiooni", });
    payloadBuilder.addKeyword ("laseraatio", new String[]{"laseraatio", "laseratio", "laseratsioni", "laseratsiooni", });
    payloadBuilder.addKeyword ("manifestaatio", new String[]{"manifestaatio", "manifestatio", "manifestatsioni", "manifestatsiooni", });
    payloadBuilder.addKeyword ("maseraatio", new String[]{"maseraatio", "maseratio", "maseratsioni", "maseratsiooni", });
    payloadBuilder.addKeyword ("maskulinisaatio", new String[]{"maskulinisaatio", "maskulinisatio", "maskulinisatsioni", "maskulinisatsiooni", });
    payloadBuilder.addKeyword ("resuskitaatio", new String[]{"resuskitaatio", "resuskitatio", "resuskitatsioni", "resuskitatsiooni", });
    payloadBuilder.addKeyword ("ulseraatio", new String[]{"ulseraatio", "ulseratio", "ulseratsioni", "ulseratsiooni", });
    payloadBuilder.addKeyword ("desinfektio", new String[]{"desinfektio", "desinfektsio", "desinfektsioni", "desinfektsiooni", });
    payloadBuilder.addKeyword ("retardaatio", new String[]{"retardaatio", "retardatio", "retardatsioni", "retardatsiooni", });
    payloadBuilder.addKeyword ("retraktio", new String[]{"retraktio", "retraktsio", "retraktsioni", "retraktsiooni", });
    payloadBuilder.addKeyword ("hydrogenaatio", new String[]{"hydrogenaatio", "hydrogenatio", "hydrogenatsioni", "hydrogenatsiooni", });
    payloadBuilder.addKeyword ("konsolidaatio", new String[]{"konsolidaatio", "konsolidatio", "konsolidatsioni", "konsolidatsiooni", });
    payloadBuilder.addKeyword ("laksaatio", new String[]{"laksaatio", "laksatio", "laksatsioni", "laksatsiooni", });
    payloadBuilder.addKeyword ("infestaatio", new String[]{"infestaatio", "infestatio", "infestatsioni", "infestatsiooni", });
    payloadBuilder.addKeyword ("obstipaatio", new String[]{"obstipaatio", "obstipatio", "obstipatsioni", "obstipatsiooni", });
    payloadBuilder.addKeyword ("opsonisaatio", new String[]{"opsonisaatio", "opsonisatio", "opsonisatsioni", "opsonisatsiooni", });
    payloadBuilder.addKeyword ("ossifikaatio", new String[]{"ossifikaatio", "ossifikatio", "ossifikatsioni", "ossifikatsiooni", });
    payloadBuilder.addKeyword ("keratinisaatio", new String[]{"keratinisaatio", "keratinisatio", "keratinisatsioni", "keratinisatsiooni", });
    payloadBuilder.addKeyword ("eksfoliaatio", new String[]{"eksfoliaatio", "eksfoliatio", "eksfoliatsioni", "eksfoliatsiooni", });
    payloadBuilder.addKeyword ("differentiaatio", new String[]{"differentiaatio", "differentiatio", "differentiatsioni", "differentiatsiooni", });
    payloadBuilder.addKeyword ("pronaatio", new String[]{"pronaatio", "pronatio", "pronatsioni", "pronatsiooni", });
    payloadBuilder.addKeyword ("regurgitaatio", new String[]{"regurgitaatio", "regurgitatio", "regurgitatsioni", "regurgitatsiooni", });
    payloadBuilder.addKeyword ("vaskularisaatio", new String[]{"vaskularisaatio", "vaskularisatio", "vaskularisatsioni", "vaskularisatsiooni", });
    payloadBuilder.addKeyword ("digitalisaatio", new String[]{"digitalisaatio", "digitalisatio", "digitalisatsioni", "digitalisatsiooni", });
    payloadBuilder.addKeyword ("eksaserbaatio", new String[]{"eksaserbaatio", "eksaserbatio", "eksaserbatsioni", "eksaserbatsiooni", });
    payloadBuilder.addKeyword ("inseminaatio", new String[]{"inseminaatio", "inseminatio", "inseminatsioni", "inseminatsiooni", });
    payloadBuilder.addKeyword ("ekstrapolaatio", new String[]{"ekstrapolaatio", "ekstrapolatio", "ekstrapolatsioni", "ekstrapolatsiooni", });
    payloadBuilder.addKeyword ("vakuolisaatio", new String[]{"vakuolisaatio", "vakuolisatio", "vakuolisatsioni", "vakuolisatsiooni", });
    payloadBuilder.addKeyword ("disseminaatio", new String[]{"disseminaatio", "disseminatio", "disseminatsioni", "disseminatsiooni", });
    payloadBuilder.addKeyword ("duplikaatio", new String[]{"duplikaatio", "duplikatio", "duplikatsioni", "duplikatsiooni", });
    payloadBuilder.addKeyword ("eksploraatio", new String[]{"eksploraatio", "eksploratio", "eksploratsioni", "eksploratsiooni", });
    payloadBuilder.addKeyword ("evakuaatio", new String[]{"evakuaatio", "evakuatio", "evakuatsioni", "evakuatsiooni", });
    payloadBuilder.addKeyword ("fenestraatio", new String[]{"fenestraatio", "fenestratio", "fenestratsioni", "fenestratsiooni", });
    payloadBuilder.addKeyword ("invaginaatio", new String[]{"invaginaatio", "invaginatio", "invaginatsioni", "invaginatsiooni", });
    payloadBuilder.addKeyword ("katetrisaatio", new String[]{"katetrisaatio", "katetrisatio", "katetrisatsioni", "katetrisatsiooni", });
    payloadBuilder.addKeyword ("klaudikaatio", new String[]{"klaudikaatio", "klaudikatio", "klaudikatsioni", "klaudikatsiooni", });
    payloadBuilder.addKeyword ("malrotaatio", new String[]{"malrotaatio", "malrotatio", "malrotatsioni", "malrotatsiooni", });
    payloadBuilder.addKeyword ("marsupialisaatio", new String[]{"marsupialisaatio", "marsupialisatio", "marsupialisatsioni", "marsupialisatsiooni", });
    payloadBuilder.addKeyword ("metylaatio", new String[]{"metylaatio", "metylatio", "metylatsioni", "metylatsiooni", });
    payloadBuilder.addKeyword ("nosiseptio", new String[]{"nosiseptio", "nosiseptsio", "nosiseptsioni", "nosiseptsiooni", });
    payloadBuilder.addKeyword ("sugillaatio", new String[]{"sugillaatio", "sugillatio", "sugillatsioni", "sugillatsiooni", });
    payloadBuilder.addKeyword ("transduktio", new String[]{"transduktio", "transduktsio", "transduktsioni", "transduktsiooni", });
    payloadBuilder.addKeyword ("repositio", new String[]{"repositio", "repositsio", "repositsioni", "repositsiooni", });
    payloadBuilder.addKeyword ("asetylaatio", new String[]{"asetylaatio", "asetylatio", "asetylatsioni", "asetylatsiooni", });
    payloadBuilder.addKeyword ("deprivaatio", new String[]{"deprivaatio", "deprivatio", "deprivatsioni", "deprivatsiooni", });
    payloadBuilder.addKeyword ("malformaatio", new String[]{"malformaatio", "malformatio", "malformatsioni", "malformatsiooni", });
    payloadBuilder.addKeyword ("myelinaatio", new String[]{"myelinaatio", "myelinatio", "myelinatsioni", "myelinatsiooni", });
    payloadBuilder.addKeyword ("trabekulaatio", new String[]{"trabekulaatio", "trabekulatio", "trabekulatsioni", "trabekulatsiooni", });
    payloadBuilder.addKeyword ("renovaatio", new String[]{"renovaatio", "renovatio", "renovatsioni", "renovatsiooni", });
    payloadBuilder.addKeyword ("reseptio", new String[]{"reseptio", "reseptsio", "reseptsioni", "reseptsiooni", });
    payloadBuilder.addKeyword ("bifurkaatio", new String[]{"bifurkaatio", "bifurkatio", "bifurkatsioni", "bifurkatsiooni", });
    payloadBuilder.addKeyword ("konisaatio", new String[]{"konisaatio", "konisatio", "konisatsioni", "konisatsiooni", });
    payloadBuilder.addKeyword ("krepitaatio", new String[]{"krepitaatio", "krepitatio", "krepitatsioni", "krepitatsiooni", });
    payloadBuilder.addKeyword ("pulsaatio", new String[]{"pulsaatio", "pulsatio", "pulsatsioni", "pulsatsiooni", });
    payloadBuilder.addKeyword ("strangulaatio", new String[]{"strangulaatio", "strangulatio", "strangulatsioni", "strangulatsiooni", });
    payloadBuilder.addKeyword ("formikaatio", new String[]{"formikaatio", "formikatio", "formikatsioni", "formikatsiooni", });
    payloadBuilder.addKeyword ("agglutinaatio", new String[]{"agglutinaatio", "agglutinatio", "agglutinatsioni", "agglutinatsiooni", });
    payloadBuilder.addKeyword ("kapasitaatio", new String[]{"kapasitaatio", "kapasitatio", "kapasitatsioni", "kapasitatsiooni", });
    payloadBuilder.addKeyword ("konfabulaatio", new String[]{"konfabulaatio", "konfabulatio", "konfabulatsioni", "konfabulatsiooni", });
    payloadBuilder.addKeyword ("introduktio", new String[]{"introduktio", "introduktsio", "introduktsioni", "introduktsiooni", });
    payloadBuilder.addKeyword ("translitteraatio", new String[]{"translitteraatio", "translitteratio", "translitteratsioni", "translitteratsiooni", });
    payloadBuilder.addKeyword ("annihilaatio", new String[]{"annihilaatio", "annihilatio", "annihilatsioni", "annihilatsiooni", });
    payloadBuilder.addKeyword ("fluktuaatio", new String[]{"fluktuaatio", "fluktuatio", "fluktuatsioni", "fluktuatsiooni", });
    payloadBuilder.addKeyword ("konfrontaatio", new String[]{"konfrontaatio", "konfrontatio", "konfrontatsioni", "konfrontatsiooni", });
    payloadBuilder.addKeyword ("karbonylaatio", new String[]{"karbonylaatio", "karbonylatio", "karbonylatsioni", "karbonylatsiooni", });
    payloadBuilder.addKeyword ("allitteraatio", new String[]{"allitteraatio", "allitteratio", "allitteratsioni", "allitteratsiooni", });
    payloadBuilder.addKeyword ("trepanaatio", new String[]{"trepanaatio", "trepanatio", "trepanatsioni", "trepanatsiooni", });
    payloadBuilder.addKeyword ("domestikaatio", new String[]{"domestikaatio", "domestikatio", "domestikatsioni", "domestikatsiooni", });
    payloadBuilder.addKeyword ("ekstirpaatio", new String[]{"ekstirpaatio", "ekstirpatio", "ekstirpatsioni", "ekstirpatsiooni", });
    payloadBuilder.addKeyword ("narraatio", new String[]{"narraatio", "narratio", "narratsioni", "narratsiooni", });
    payloadBuilder.addKeyword ("enukleaatio", new String[]{"enukleaatio", "enukleatio", "enukleatsioni", "enukleatsiooni", });
    payloadBuilder.addKeyword ("lateralisaatio", new String[]{"lateralisaatio", "lateralisatio", "lateralisatsioni", "lateralisatsiooni", });
    payloadBuilder.addKeyword ("myelinisaatio", new String[]{"myelinisaatio", "myelinisatio", "myelinisatsioni", "myelinisatsiooni", });
    payloadBuilder.addKeyword ("palliaatio", new String[]{"palliaatio", "palliatio", "palliatsioni", "palliatsiooni", });
    payloadBuilder.addKeyword ("stigmatisaatio", new String[]{"stigmatisaatio", "stigmatisatio", "stigmatisatsioni", "stigmatisatsiooni", });
    payloadBuilder.addKeyword ("vegetaatio", new String[]{"vegetaatio", "vegetatio", "vegetatsioni", "vegetatsiooni", });
    payloadBuilder.addKeyword ("vitrifikaatio", new String[]{"vitrifikaatio", "vitrifikatio", "vitrifikatsioni", "vitrifikatsiooni", });
    payloadBuilder.addKeyword ("deklaraatio", new String[]{"deklaraatio", "deklaratio", "deklaratsioni", "deklaratsiooni", });
    payloadBuilder.addKeyword ("destruktio", new String[]{"destruktio", "destruktsio", "destruktsioni", "destruktsiooni", });
    payloadBuilder.addKeyword ("eskalaatio", new String[]{"eskalaatio", "eskalatio", "eskalatsioni", "eskalatsiooni", });
    payloadBuilder.addKeyword ("inokulaatio", new String[]{"inokulaatio", "inokulatio", "inokulatsioni", "inokulatsiooni", });
    payloadBuilder.addKeyword ("elongaatio", new String[]{"elongaatio", "elongatio", "elongatsioni", "elongatsiooni", });
    payloadBuilder.addKeyword ("desorptio", new String[]{"desorptio", "desorptsio", "desorptsioni", "desorptsiooni", });
    payloadBuilder.addKeyword ("insolaatio", new String[]{"insolaatio", "insolatio", "insolatsioni", "insolatsiooni", });
    payloadBuilder.addKeyword ("kanonisaatio", new String[]{"kanonisaatio", "kanonisatio", "kanonisatsioni", "kanonisatsiooni", });
    payloadBuilder.addKeyword ("kontemplaatio", new String[]{"kontemplaatio", "kontemplatio", "kontemplatsioni", "kontemplatsiooni", });
    payloadBuilder.addKeyword ("polymeraatio", new String[]{"polymeraatio", "polymeratio", "polymeratsioni", "polymeratsiooni", });
    payloadBuilder.addKeyword ("ammonifikaatio", new String[]{"ammonifikaatio", "ammonifikatio", "ammonifikatsioni", "ammonifikatsiooni", });
    payloadBuilder.addKeyword ("saltaatio", new String[]{"saltaatio", "saltatio", "saltatsioni", "saltatsiooni", });
    payloadBuilder.addKeyword ("demetylaatio", new String[]{"demetylaatio", "demetylatio", "demetylatsioni", "demetylatsiooni", });
    payloadBuilder.addKeyword ("glykosylaatio", new String[]{"glykosylaatio", "glykosylatio", "glykosylatsioni", "glykosylatsiooni", });
    payloadBuilder.addKeyword ("gastrulaatio", new String[]{"gastrulaatio", "gastrulatio", "gastrulatsioni", "gastrulatsiooni", });
    payloadBuilder.addKeyword ("konurbaatio", new String[]{"konurbaatio", "konurbatio", "konurbatsioni", "konurbatsiooni", });
    payloadBuilder.addKeyword ("inklinaatio", new String[]{"inklinaatio", "inklinatio", "inklinatsioni", "inklinatsiooni", });
    payloadBuilder.addKeyword ("affektio", new String[]{"affektio", "affektsio", "affektsioni", "affektsiooni", });
    payloadBuilder.addKeyword ("emanaatio", new String[]{"emanaatio", "emanatio", "emanatsioni", "emanatsiooni", });
    payloadBuilder.addKeyword ("transitio", new String[]{"transitio", "transitsio", "transitsioni", "transitsiooni", });
    payloadBuilder.addKeyword ("islamisaatio", new String[]{"islamisaatio", "islamisatio", "islamisatsioni", "islamisatsiooni", });
    payloadBuilder.addKeyword ("suppositio", new String[]{"suppositio", "suppositsio", "suppositsioni", "suppositsiooni", });
    payloadBuilder.addKeyword ("alkylaatio", new String[]{"alkylaatio", "alkylatio", "alkylatsioni", "alkylatsiooni", });
    payloadBuilder.addKeyword ("akklimatisaatio", new String[]{"akklimatisaatio", "akklimatisatio", "akklimatisatsioni", "akklimatisatsiooni", });
    payloadBuilder.addKeyword ("sedimentaatio", new String[]{"sedimentaatio", "sedimentatio", "sedimentatsioni", "sedimentatsiooni", });
    payloadBuilder.addKeyword ("sanitaatio", new String[]{"sanitaatio", "sanitatio", "sanitatsioni", "sanitatsiooni", });
    payloadBuilder.addKeyword ("kompilaatio", new String[]{"kompilaatio", "kompilatio", "kompilatsioni", "kompilatsiooni", });
    payloadBuilder.addKeyword ("relegaatio", new String[]{"relegaatio", "relegatio", "relegatsioni", "relegatsiooni", });
    payloadBuilder.addKeyword ("kollaboraatio", new String[]{"kollaboraatio", "kollaboratio", "kollaboratsioni", "kollaboratsiooni", });
    payloadBuilder.addKeyword ("kollineaatio", new String[]{"kollineaatio", "kollineatio", "kollineatsioni", "kollineatsiooni", });
    payloadTrie = payloadBuilder.build();
  };
}
